### ISSUE TITLE
top by device-type

### ISSUE THREAD

**Issue by abgit** [allinurl/goaccess#10]
This is a counter that will group hits by device type.
And, at least we have 3 access types:
1: desktop
2: mobile devices
3: other (eg: crawlers)

Very useful on analytics to apply some strategy.

desktop: X hits ( x%)
mobile: Y hits (y%)
other: Z hits (z%)

**Comment by overnine** [comment]
@allinurl I think perhaps it would be a good idea to consider reopening this issue?

We would love to have device type information in the JSON output, or alternatively pure UA strings grouped somehow perhaps? I.e. It would be nice to have Windows NT 6.3; ARM (Or those with touch identifiers perhaps?) type devices not just classified as windows, but rather surface devices and so forth imo?

**Comment by aphorise** [comment]
Just a thought for the longer term - can we strive to provide a comprehensive / near complete *_device coverage_*? - if we'd have a conscience lexical parallel of `Device`:__to__:`Browser` even with __manufactor specific__ / __vendor specific__ pollutants :smile: (ms, vs). I'd approximate that a database with ~10k-18k of known *_devices_* out there would be a 97%+ coverage of all thats mobile & maybe in circulation from __`NetFront`__, __`HTML4`__, __`Java`__, __`MMS`__, __`SymbianOS`__, __`WAP`__, __`WEB`__, __`WHL`__, __`Windows`__, __`WindowsCE`__, etc...

Using a few known listings & articles ([0](http://www.botsvsbrowsers.com/), [1](http://www.zytrax.com/tech/web/mobile_ids.html), [2](http://www.developershome.com/wap/detection/detection.asp?page=userAgentHeader), [3](https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent), [4](http://www.mobilemultimedia.be/en/mobile-phone-user-agent)) as guide the following lexicon may be a good start:

| UA keyword | device | full UA sample string of a specific device |
| ------------- | ------------- | ------------- |
| __`UP.`__ / __`up.b`__ / __`up/`__  | Openwave Mobile Browser / telephone  | `AUDIOVOX-CDM-8915 UP.Browser/6.2.2.6.h.1.102 (GUI) MMP/2.0` |
| __`BlackBerry`__, __` BlackBerry `__, __`UP.`__, __`up.b`__, __`up/`__  *_vs_* | BlackBerry device / telephone | `BlackBerry6510/4.0.0 UP.Browser/5.0.3.3` |
| __` HP `__, __`hp-tablet`__ _or_ *_msvs_* | HP device / telephone | `HTC_Touch_HD_T8282 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11)` |
| __` HP `__, __`hp-tablet`__ _or_ *_msvs_* | HP device / telephone | `Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; PPC; 240x320)` |
| __` HTC `__, __`HTC_`__, __`HTC-`__ _or_ *_msvs_* | HTC device / telephone | `HTC_Touch_HD_T8282 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11)` |
| __` HTC `__, __`HTC_`__, __`HTC-`__ _or_ *_msvs_* | HTC device / telephone | `HTC_S310-Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; Smartphone; 176x220)` |
| __`LGE`__, __`LG-`__, __`lg-`__, __`LG/`__ | LGE tablet / telephone | `LG-T300/V100 Obigo/Q7.3 MMS/LG-MMS-V1.1/1.2 MediaPlayer/LGPlayer/1.0 Java/ASVM/1.1 Profile/MIDP-2.1 Configuration/C` |
| __`LGE`__, __`LG-`__, __`lg-`__, __`LG/`__ | LGE tablet / telephone | `Mozilla/5.0 (Linux; Android 4.1.2; LG-P760 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.99 Mobile Safari/537.36` |
| __`SAMSUMNG`__, __`samsung`__, __`sam-`__, __`sam`__ _or_ *_msvs_* | Samsung tablet / telephone | `SAMSUNG-SGH-A737/UCGI3 SHP/VPP/R5 NetFront/3.4 SMM-MMS/1.2.0 profile/MIDP-2.0 configuration/CLDC-1.1 UP.Link/6.3.0.0.0` |
| __`SAMSUMNG`__, __`samsung`__, __`sam-`__, __`sam`__ _or_ *_msvs_* | Samsung tablet / telephone | `samr810 Netfront/3.4 Mozilla/5.0 like Gecko/20060426` |
| __`sie-`__, __`SIE-`__ | Siemens telephone | ` SIE-SK6R/46 UP.Browser/7.0.2.2.d.1.100(GUI) MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1` |
| __`SonyEricsson`__, __`sonyericsson`__, __`Sony Tablet`__, _or_ *_msvs_* | SonyEricsson  tablet / telephone | `SonyEricssonK608i/R2BA Browser/SEMC-Browser/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1` |
| __`SonyEricsson`__, __`sonyericsson`__, __`Sony Tablet`__, _or_ *_msvs_* | SonyEricsson  tablet / telephone | ` SonyEricssonK608i/R301 Profile/MIDP-1.0 Configuration/CLDC-1.0` |

A complete device focused list of manufacturers & relevant providers in the global context could comprises of approximately ~ __`142`__ with more UA's by distributor / OEM ? :

| A-Z of makes & vendors |
| ------------- |
| `Acer`, `Airness`, `Alcatel`, `Allview`, `Amazon`, `Amoi`, `Apple`, `Asus`, `AT&T`, `Audiovox`|
| `BlackBerry / RIM `, `Benefon`, `Benq`, `Benq-siemens`, `Bird`, `BLU`, `Bosch` |
| `Casio`, `Cat`, `Celkon`, `Chea`, `Coolpad`, `Cricket`, `Dell`, `DoCoMo (NTT Mobile)` |
| `EE`, `Elson`, `Emporia`, `Emblaze`, `Energizer`, `Ericsson`, `Eten`, `Ezio`, `Ezze` |
| `Fly`, `Foxconn`, `Fujitsu Siemens`, `G3`, `Garmin-asus`, `Gigabyte`, `Gionee` |
| `Haier`, `HP`, `HTC`, `Huawei`, `Jolla` |
| `I-mate`, `I-mobile`, `Icemobile`, `Innostream`, `iNQ`, `Intex` |
| `Konka`, `Kyocera`, `Karbonn`, `Lava`, `Lenovo`, `LGE` |
| `Maxon`, `Maxwest`, `Meizu`, `Micromax`, `Microsoft`, `Mitac`, `Mitsubishi`, `Mobilexp`, `Mobistel`, `Modelabs`, `Modu`, `MWg`, `Motorola`, `My Way` |
| `Nec`, `Neonode`, `Nintendo`, `NIU`, `Nokia`, `nook`, `Nvidia`, `O2`, `Obigo`, `Onda`, `Orange`, `OnePlus`, `Oppo` |
| `Palm`, `Panasonic`, `Pantech`, `Parla`, `Philips`, `Phoneone`, `Psion`, `Plum`, `Posh`, `Prestigio`, `QMobile`, `Qtek` |
| `Sagem`, `Samart`, `Samsung`, `Sanyo`, `Sec`, `Sendo`, `Sewon`, `Sharp`, `Siemens`, `Skyspring`, `Sonim`, `Sonim`, `Sony`, `Sony Ericsson`, `Spice`, `Sprint`, `SPV` |
| `T-mobile`, `Tel.Me.`, `Techfaith`, `Thuraya`, `Toshiba` |
| `UCWEB`, `Uniscope`, `Uriver`, `Utec`, `Utstarcom`, `Vertu`, `verykool`, `Virgin`, `Vitelcom`, `Vivo`, `Vk Mobile`, `Vodafone`, `Voxtel` |
| `Wellcom`, `Wiko`, `WND`, `XCute`, `Xiaomi`, `XOLO`, `Yezz`, `Yota`, `YU`, `ZTE` |

This list *__excludes__* all potential UA such as those by service, application, proxy, etc, from the [1.5+ million](http://www.botsvsbrowsers.com/) (& growing) already classified in some directories with others yet to emerge for vehicle / automotive (your car) and television (not sure how unique these are) systems.

I can help in the compilation of the proposed DB.

**Comment by allinurl** [comment]
@overnine assuming we still want to use the ones posted above, i.e., `desktop`, `mobile`, `others` then I think we could add this as a new panel. Categorizing this could be tricky. Are those the only categories we could use? Should we have `tablets` as well?

@aphorise having a comprehensive list of browsers and OSs would be awesome, but we may need to refactor [`browsers.c`](https://github.com/allinurl/goaccess/blob/master/src/browsers.c) & [`opesys.c`](https://github.com/allinurl/goaccess/blob/master/src/opesys.c) since currently those are bottlenecks. (the size of the list is proportional to the run time, which makes them slow). We could have a large list mapped in a hash but it would need to be a full match search. Or `bsearch` perhaps?

For the record, this may be related to #152.

**Comment by overnine** [comment]
@allinurl i only use goaccess for the json output, i dont really have any considerations in terms of usability of the curse interface. Also the most comprehensive resource i know of which handles this is https://github.com/serbanghita/Mobile-Detect

**Comment by aphorise** [comment]
@allinurl - I actually think we can do this adaptively / build on a global `browser` & `device` context. So instead of having fixed size `table` / `bsearch` or `hash` - have a `tree` that spans / adaptively increases based on new / differing UA's that read and that would only get a naive  comparison against a master UA-DB  / record once. 

So basically the the UA-DB (lexicon) can have two focuses:
- by device (as per earlier comment & proposal) - that'd be a potential look up of `1` in ~ `18``k` (estimate). 
- by service or anything else (as per known & remaining lot in excess of a million)  - that'd be a potential look up of `1` in ~ `1.4``m` (estimate).

The ideal UA lexicon that would be ( __`adaptive-UA`__) adaptively built from the data-set (logs) being parsed and could be an `O(n)` algorithm if its stored in a`hash` or a `O(n^2)` if its in some other from (`btree`, `link-list`); either-way the scope of any set in most cases should be less than `<`  __`complete-UA`__ `O(n) or O(n^2)`thats the total space / list of everything thats known & can be targeted. 

What'd be even smarted for `real-time` stats & scenarios where _`adaptive-UA`_ can / may grow indefinably would be to have a `stack`-limit to a reasonable size `2^32` or `65535` - thereby dropping any single / one time occurrences; all that would be needed is a `FIFO` / `FILO` (first-in-first-out / first-in-last-out) precedence on the lower portion (say a reserve of `255`)  so as to always accommodate and record new / single `1` time agents that would always register and would be visible in the most recent time-frames. Ditto governing rules for what can move up the _`adaptive-UA`_

I hope I'm  clearing conveying the intent.

**Comment by aphorise** [comment]
For reference the RAM / __memory__ space requirements to hold all potential UA can be expressed as:

| # | __for 65535 records__ |
| ---- | ---- |
|  | __`MAX`__  / _unlikely_ case |
| `(2^16)-1`=__`65,535`__ | `bytes` per record max |
| `65535^2`=__`4,294,836,225`__ | `bytes` (__`~``4``Gbytes`__) |
|  | __`AVG q3`__ / _possible_ upper-quartile |
| `(2^11)-1`=__`2,047`__ | `bytes` per record avg-q3 |
| `2,047*65535`=__`134,150,145`__ | `bytes` (__`~``134``Mbytes`__) |
| | __`AVG q1`__ / _possible_ lower-quartile |
| `(2^9)-1`=__`511`__ | `bytes` per record avg-q1 |
| `511*65535`=__`33,553,920`__ | `bytes` (`~`__`33``Mbytes`__) |
| | __`AVG`__ / _common_ sub-or-at-average |
| `(2^8)-1`=__`255`__ | `bytes` per record real average |
| `255*65535`=__`16,711,425`__ | `bytes` (__`~``16``Mbytes`__) |


This is on the assumption that no UA are alike (all unique for `2^16-1`) and that none shall ever exceed `64``Kbytes` which is unreasonably high & frankly even graver than stupid if neared or exceed. The most obvious candidates of illogical uses which tend to exceed the common `512`-`1024` (bytes) are for example *__I__*nternet-*__E__*xplorer (`IE`) or other `debug` or `build` specific text that may be embedded as part of the UA identifier - even these tend to be < [`8``Kbytes` at worse](http://stackoverflow.com/a/6595973).

A few other rules can also be applied as objectively determinates anything that may not match but may for example be found in one of a few known criteria scope of `device` `&/or` `browser` :
- _DEVICE_: 1 of 143 manufacturer-UA
- _BROWSER_:1 of < ~ 64 application-UA `chrome`/`blink` et al, `firedox` et al, `geko`, `trident` / `IE` / `MOSIAC`, `Netscape`, `Opera`, `Safari`, `Webkit`, etc.
