### ISSUE TITLE
How to hide IP (make report anonymous)

### ISSUE THREAD

**Issue by karibuTW** [allinurl/goaccess#1009]
Hello,

I'm the mirror of some projects and I provide accessible stats with goaccess to the dev.
However I wish to hide the visitors IPs for privacy reason. Especially when we start to touch projects like Tor, Tails, etc..

I'm using a script at the moment to replace the IPs with x.x.x.x, but I guess it could be a good feature for goaccess directly.
May be it exists already but I haven't seen it.

Thanks for your ideas there.

**Comment by allinurl** [comment]
Great question. Currently it doesn't have this feature. I can look into it, shouldn't be too bad to implement this. Thanks for bring this up.

**Comment by stitch** [comment]
Awesome :)

I hope this might provide more context to a request like this:

IP addresses are often seen as personal data and referral urls can contain sensitive information too, especially when they can be related to a website or service. Our wish is to publish the goacces statistics on a website for the world to see. We'd like to publish all dashboards of course, to show of all awesome stats.

Currently our quick workaround would be to filter the output. This solution is not future proof, as ip-addresses and other info might pop up elsewhere in the next update.

Ideally i would see a feature that would transform all sensitive information into unique but meaningless (non-reversable) hashes or removed all-together. Ideally this would be a single flag you set to all relevant panels ("--private"). When thinking of privacy by design, this would be default behavior.

**Comment by allinurl** [comment]
The ability to anonymize IPv4/6 addresses has been added. This is done at the the output level so all visitors stats will continue to show accurate numbers. e.g.,

    192.168.1.100 => 192.168.1.0

**Comment by allinurl** [comment]
BTW, feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test this out, otherwise it will be pushed out in the upcoming release.

**Comment by allinurl** [comment]
@BobVul [Due by November 23, 2018](https://github.com/allinurl/goaccess/milestone/1)

**Comment by karibuTW** [comment]
Hello,?
I've installed goaccess from repo (Debian), v1.4 and the IP of the users are visible. How should we add it?
I think it should be hidden by default for privacy reasons.

Possible?

Thank you

**Comment by devmetall** [comment]
Hi All
Please help me
goaccess: unrecognized option '--anonymize-level=3'

**Comment by allinurl** [comment]
> Hi All Please help me goaccess: unrecognized option '--anonymize-level=3'

Sounds like you are running an older version; you will need to upgrade to the latest version.
