### ISSUE TITLE
Use GeoIP2 in distributed builds

### ISSUE THREAD

**Issue by Alex131089** [allinurl/goaccess#1085]
I'm trying goaccess today, but I'm encountering the following errors: 
```
Error Traversing Database for ipnum = [..] - Perhaps database is corrupt?
```

While I found #620, it seems it's because I'm trying to use a GeoIP2 DB with the debian/ubuntu build, which seems to be built for the legacy format (is it possible to find the build arguments ?).

If I'm not mistaken, could you build the distributed versions against GeoIP2, especially since [MaxMind announced the legacy format is deprecated](https://dev.maxmind.com/geoip/geoip2/geolite2/)?

**Comment by allinurl** [comment]
Good question. You can certainly build with GeoIP2 support. Please take a look at the [configuration options](https://goaccess.io/man#configuration) for details.

```
$ cd goaccess-1.2/
$ ./configure --enable-utf8 --enable-geoip=mmdb
$ make
# make install
```

**Comment by Alex131089** [comment]
I'll stick with the distributed one for the moment, but I'll be ready to switch :)

Btw, thank you for this, really good & lighter alternative to Piwik (Matomo now) used in the same way (fed by log files & not using tracker)!
I'm using the following setup: https://gist.github.com/Alex131089/92285c29668e73d74a0f24b47b6b809b if it can be useful in any way (I had to try/dig to really understand the `agent-list`, `real-os` and `std-geoip` though).

**Comment by allinurl** [comment]
Thanks for sharing that :) 

Eventually I do plan to build with GeoIP2 for the deb binaries, I just want to make sure debian and ubuntu stable offer GeoIP2 as part of their available packages.

**Comment by svenba** [comment]
The legacy db is very outdated. Any update on this?

**Comment by allinurl** [comment]
@svenba mmdb will be pushed out in the upcoming binary release.

**Comment by svenba** [comment]
v1.3 was released on Nov 23, 2018.

Is there an ETA for the next release?

**Comment by allinurl** [comment]
@svenba I completely agree that this coming release is way behind. Though, I'm 2/3 the way onto finishing the new on-disk storage, which is the main change I've been meaning to push out since early v1. That would clear the way for a lot of updates/changes that are in the pipeline. If it all goes well, it would be before or by the end of March.

**Comment by allinurl** [comment]
[**v1.4**](https://goaccess.io/download) is out!  GeoIP2 ships by default. Available as well in the deb repo for the following distributions: 

```
goaccess |  1:1.4-xenial |  xenial | amd64, i386
goaccess |  1:1.4-bionic |  bionic | amd64
goaccess |    1:1.4-eoan |    eoan | amd64
goaccess |   1:1.4-focal |   focal | amd64
goaccess | 1:1.4-stretch | stretch | amd64, i386
goaccess |  1:1.4-buster |  buster | amd64, i386
```
If you get a `GPG error The following signatures couldn't be verified because the public key is not available.` Please make sure to download the new public key as shown [**here**](https://goaccess.io/download#official-repo) above to correct this.
