### ISSUE TITLE
Can I custom options of http_user_agent?

### ISSUE THREAD

**Issue by Haitianisgood** [allinurl/goaccess#1207]
env:

goaccess1.2

The  data colume of "OPERATING SYSTEMS" Panel have too many "Unknow"

I think data colume of "OPERATING SYSTEMS" is corresponds to "http_user_agent"!

I see  http_user_agent  have Android，ios，Windows...

Can I custom options of http_user_agent?

For example:

I want to add a app-version-0.1 to http_user_agent

**Comment by allinurl** [comment]
Yes, you can add more options to the OS list. Take a look at this [file](https://github.com/allinurl/goaccess/blob/master/src/opesys.c), note that you will need to recompile after making those changes.

Can you please post a screenshot of the issue you are having?

**Comment by Haitianisgood** [comment]
![goaccess](https://user-images.githubusercontent.com/9413884/44438552-31bdef80-a5f2-11e8-8f0f-b7ef11b41b1f.jpg)

I  know C not well!My http_user_agent like "app/0.1.1"

**Comment by allinurl** [comment]
It's pretty simple, just add it to the category you would like it to be under. You can copy one of the lines in there. Then just build again with:

```
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install
```

As far as too many Unknown OSs, usually this is an indication that there are a lot of bots, since goaccess doesn't know what OS those bots are running, then it marks them as Unknown. If you know the specific bot and know the OS that should be, feel free to add it or post them here.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by Haitianisgood** [comment]
I have many http_user_agent like "app/0.1.1" 、"app/1.1.0"、"app/2.1.1" and I want to get the release of app!

Whether I add to a method like "get_real_android"?

**Comment by allinurl** [comment]
You can simply add `app` to the list as I mentioned above and it will automatically get the release/version number.

**Comment by Haitianisgood** [comment]
Thank you very much for you reply!

I have solved by your advice!
