### ISSUE TITLE
cron problem due to missing path

### ISSUE THREAD

**Issue by egy1st** [allinurl/goaccess#1214]
I try to run this cron job but goaccess can not creat the report,
*/2 * * * * goaccess access.log -a > report.html 
although when i run this command from my ssh it works fine

**Comment by LoZio** [comment]
Mostly due to missing path entries when run via crond.
Chech which is the full path of goaccess:  `which goaccess`
You'll get something like: `/usr/local/bin/goaccess`
In your cron line use the full path above instead of just `goaccess`.
`*/2 * * * * /usr/local/bin/goaccess access.log -a > report.html`

**Comment by egy1st** [comment]
Thank you. it works now
