### ISSUE TITLE
Parsing... [x,xxx,xxx] [8,600/s]  is that normal?

### ISSUE THREAD

**Issue by MM629** [allinurl/goaccess#1233]
I feel its too slowly. How can I speed up it.

> 
Benchmark (v1.2) - Default Hash Tables | 51,394 lines per second
-- | --

I

**Comment by allinurl** [comment]
What are your machine specs? and what command & options are you passing?

**Comment by MM629** [comment]
Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
16GB RAM

goaccess -c access.log

**Comment by MM629** [comment]
and I tried with -p options, almost same.

**Comment by allinurl** [comment]
This is probably bound to your processor, disk and possibly log. You could try running it with `--no-global-config` and simply specify the log and log-format and see how that runs. Also, you could use `-q` to strip the query part from the request and see if it helps. Here's my output on an i7 machine.

[![asciicast](https://asciinema.org/a/KCrjY5fYuYUlwk0PibgBbzDQn.png)](https://asciinema.org/a/KCrjY5fYuYUlwk0PibgBbzDQn)

**Comment by MM629** [comment]
Parsing... [250,475] [9,276/s]

goaccess --no-global-config -c -q localhost_access.log

It looks like 10% faster. 

BTW: goaccess was installed by apt. Do I need use source code to install again?

**Comment by allinurl** [comment]
You could try but I don't think there would be a major difference if any.

**Comment by allinurl** [comment]
Also please try:

`--ignore-panel=OS` `--ignore-panel=BROWSERS`
or only 
`--ignore-panel=OS`
or only
`--ignore-panel=BROWSERS`

In addition:

1. Use `-g` to use the standard GeoIP database for less memory usage (if using geolocation). 
2. Use `-q` to strip the request's query string. If you have a lot of timestamped requests, and you don't need these on the report, then this flag would help. 
3. Do you need all panels? Otherwise, you could disable some of them on the config file. Panels that consume most of the ram are `REQUESTS`, `REQUESTS_STATIC`, `NOT_FOUND`, `REFERRERS`.
4. Avoid using `-a` since it will store every user agent a host has.

Closing this. Feel free to post any additional comments or reopen it if needed.
