### ISSUE TITLE
No date format was found on your conf file

### ISSUE THREAD

**Issue by andy15703166** [allinurl/goaccess#136]
When I run “goaccess -f access_log -a > report.html” It alerts:

```
Error occured at: parser.c - parse_log - 1043
No date format was found on your conf file.
```

How can I make it work? Thank you

**Comment by FrontierPsychiatrist** [comment]
I get the same error message even though I'm passing a date format via the `--date-format` parameter.
```
goaccess --log-format="%h %^[%d:%^] \"%r\" %s %b \"%R\" \"%u\"" --date-format=%d/%b/%Y -f 2015.log
```

**Comment by allinurl** [comment]
Try passing `--no-global-config`. Also, what version are you using? Feel free to post a few lines from your access log if that does not do it.

**Comment by FrontierPsychiatrist** [comment]
That also didn't help. Here's the version I'm using:
GoAccess - version 0.9 - Apr 15 2015 01:59:02

I've installed it via homebrew under OSX Yosemite, meaning the global config is in /usr/local/etc

This happend after the update I think (hadn't used it in a while). I also tried uncommenting the lines in the config but that still didn't work.

Also, I'm redirecting the output to an HTML file. If I open the log file in the ncurses mode it works.

Here are some lines from the log
{code}
188.165.15.97 - - [01/Apr/2015:01:05:04 +0200] "GET /api/0.5.0/api.html HTTP/1.1" 200 21907 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)"
2.106.55.68 - - [01/Apr/2015:01:32:07 +0200] "GET / HTTP/1.1" 200 4282 "https://www.google.dk/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
2.106.55.68 - - [01/Apr/2015:01:32:07 +0200] "GET /css/main.css HTTP/1.1" 200 97 "http://www.node-spotify.com/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
{code}

**Comment by allinurl** [comment]
Could you try uncommenting the log, date and time format from your config file and using `-p /path/goaccess.conf` and see if that works. It sounds like the config file is overwriting the command line options.

**Comment by FrontierPsychiatrist** [comment]
Ok, I feel a bit stupid now, I didn't get the _exact_ same error message, actually the time format was missing. So I added --time-format=... to my call and everything's perfect. Sorry for wasting your time!

**Comment by warb2n** [comment]
Hello!
When i update my access i have error
> Fatal error has occurred
Error occured at: src/parser.c - verify_formats - 1691
No time format was found on your conf file.   

I use nginix and i have access 0.9.2 with stand. config file. What i need to do?

**Comment by allinurl** [comment]
@warb2n you will need to edit your goaccess config file (v0.9.2) and make sure to uncomment line 12 and 28, 48. Here's more info about this: http://goaccess.io/faq#howto-config

Let me know how it goes...

**Comment by warb2n** [comment]
@allinurl  oh i forgot line 12 bit thx!

**Comment by jayprakashstar** [comment]
I have commentated line for date format as well as log format but ti doesn't work

**Comment by allinurl** [comment]
@jayprakashstar Can you please post your config file and the location of it, e.g., `/etc/goaccess.conf`, ~/.goaccessrc.

**Comment by jayprakashstar** [comment]
######################################
# Date/Time Format Options
######################################

# The time as %H:%M:%S
#
# The hour (24-hour clock) [00,23]; leading zeros are permitted but not required.
# The minute [00,59]; leading zeros are permitted but not required.
# The seconds [00,60]; leading zeros are permitted but not required.
# See `man strftime` for more details
#
time-format %H:%M:%S
#
# Google Cloud Storage or
# The time that the request was completed, in microseconds since the Unix
# epoch.
#
#time-format %f
#
# The date_format variable followed by a space, specifies
# the log format date containing any combination of regular
# characters and special format specifiers. They all begin with a
# percentage (%) sign. See `man strftime`
#
# Apache log date format. The following date format works with any
# of the Apache's log formats below.
#
date-format %d/%b/%Y
#
# AWS | Amazon CloudFront (Download Distribution)
# AWS | Elastic Load Balancing
# W3C (IIS)
#
#date-format %Y-%m-%d
#
# Google Cloud Storage or
# The time that the request was completed, in microseconds since the Unix
# epoch.
#
#date-format %f

######################################
# Log Format Options
######################################

# The log_format variable followed by a space or \t for
# tab-delimited, specifies the log format string.
#
# NOTE: If the time/date is a timestamp in seconds or microseconds
# %x must be used instead of %d & %t to represent the date & time.
#
# NCSA Combined Log Format
#
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
#
# NCSA Combined Log Format with Virtual Host
#
#log-format %^:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
#
# Common Log Format (CLF)
#
#log-format %h %^[%d:%t %^] "%r" %s %b
#
# Common Log Format (CLF) with Virtual Host
#
#log-format %^:%^ %h %^[%d:%t %^] "%r" %s %b
#
# W3C
#
#log-format %d %t %h %^ %^ %^ %^ %r %^ %s %b %^ %^ %u %R
#
# AWS | Amazon CloudFront (Download Distribution)
#
#log-format %d\t%t\t%^\t%b\t%h\t%m\t%^\t%r\t%s\t%R\t%u\t%^
#
# AWS | Elastic Load Balancing
#
#log-format %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"
#
# Google Cloud Storage
#
#log-format "%x","%h",%^,%^,"%m","%U","%s",%^,"%b","%D",%^,"%R","%u"

######################################
# UI Options
######################################

# Prompt log/date configuration window on program start.
#
config-dialog false

# Choose among color schemes
# 1 : Default grey scheme
# 2 : Green scheme
#
color-scheme 1

# Color highlight active panel.
#
hl-header true

# Set HTML report page title and header.
#
#html-report-title My Awesome Web Stats

# Turn off colored output. This is the  default output on
# terminals that do not support colors.
# true  : for no color output
# false : use color-scheme
#
no-color false

# Don't write column names in the terminal output. By default, it displays
# column names for each available metric in every panel.
#
no-column-names false

# Disable progress metrics.
#
no-progress false

# Enable mouse support on main dashboard.
#
with-mouse false

# Disable summary metrics on the CSV output..
#
no-csv-summary false

# Custom colors for the terminal output
# Tailor GoAccess to suit your own tastes.
#
# Color Syntax:
# DEFINITION space/tab colorFG#:colorBG# [attributes,PANEL]
#
# FG# = foreground color number [-1...255] (-1 = default terminal color)
# BG# = background color number [-1...255] (-1 = default terminal color)
#
# Optionally:
#
# It is possible to apply color attributes, such as:
# bold,underline,normal,reverse,blink.
# Multiple attributes are comma separated
#
# If desired, it is possible to apply custom colors per panel, that is, a
# metric in the REQUESTS panel can be of color A, while the same metric in the
# BROWSERS panel can be of color B.
#
# The following is a 256 color scheme (Monokai palette)
#
#color COLOR_MTRC_HITS     color197:color-1
#color COLOR_MTRC_VISITORS color148:color-1
#color COLOR_MTRC_DATA     color7:color-1
#color COLOR_MTRC_BW       color81:color-1
#color COLOR_MTRC_AVGTS    color247:color-1
#color COLOR_MTRC_CUMTS    color95:color-1
#color COLOR_MTRC_MAXTS    color186:color-1
#color COLOR_MTRC_PROT     color141:color-1
#color COLOR_MTRC_MTHD     color81:color-1
#color COLOR_MTRC_PERC     color186:color-1
#color COLOR_MTRC_PERC     color186:color-1 VISITORS
#color COLOR_MTRC_PERC     color186:color-1 OS
#color COLOR_MTRC_PERC     color186:color-1 BROWSERS
#color COLOR_MTRC_PERC     color186:color-1 VISIT_TIMES
#color COLOR_MTRC_PERC_MAX color208:color-1
#color COLOR_MTRC_PERC_MAX color208:color-1 VISITORS
#color COLOR_MTRC_PERC_MAX color208:color-1 OS
#color COLOR_MTRC_PERC_MAX color208:color-1 BROWSERS
#color COLOR_MTRC_PERC_MAX color208:color-1 VISIT_TIMES
#color COLOR_PANEL_COLS    color242:color-1
#color COLOR_BARS          color186:color-1
#color COLOR_ERROR         color231:color197
#color COLOR_SELECTED      color0:color215
#color COLOR_PANEL_ACTIVE  color7:color240
#color COLOR_PANEL_HEADER  color7:color237
#color COLOR_PANEL_DESC    color242:color-1
#color COLOR_OVERALL_LBLS  color251:color-1
#color COLOR_OVERALL_VALS  color148:color-1
#color COLOR_OVERALL_PATH  color186:color-1
#color COLOR_ACTIVE_LABEL  color7:color237
#color COLOR_BG            color7:color-1
#color COLOR_DEFAULT       color7:color-1
#color COLOR_PROGRESS      color7:color141

######################################
# File Options
######################################

# Specify the path to the input log file. If set, it will take
# priority over -f from the command line.
#
#log-file /var/log/apache2/access.log

# Send all debug messages to the specified file. Needs to configured
# with --enable-debug
#
#debug-file debug.log

# Specify a custom configuration file to use. If set, it will take
# priority over the global configuration file (if any).
#
#config-file <filename>

# Log invalid requests to the specified file.
#
#invalid-requests <filename>

# Do not load the global configuration file.
#
#no-global-config false

######################################
# Parse Options
######################################

# Consider the following extensions as static files
# The actual '.' is required and extensions are case sensitive
#
static-file .css
static-file .CSS
static-file .dae
static-file .DAE
static-file .eot
static-file .EOT
static-file .gif
static-file .GIF
static-file .ico
static-file .ICO
static-file .jpeg
static-file .JPEG
static-file .jpg
static-file .JPG
static-file .js
static-file .JS
static-file .map
static-file .MAP
static-file .mp3
static-file .MP3
static-file .pdf
static-file .PDF
static-file .png
static-file .PNG
static-file .svg
static-file .SVG
static-file .swf
static-file .SWF
static-file .ttf
static-file .TTF
static-file .txt
static-file .TXT
static-file .woff
static-file .WOFF

# Exclude an IPv4 or IPv6 from being counted.
# Ranges can be included as well using a dash in between
# the IPs (start-end).
#
#exclude-ip 127.0.0.1
#exclude-ip 192.168.0.1-192.168.0.100
#exclude-ip ::1
#exclude-ip 0:0:0:0:0:ffff:808:804-0:0:0:0:0:ffff:808:808

# Enable a list of user-agents by host. For faster parsing, do not
# enable this flag.
#
agent-list false

# Include HTTP request method if found. This will create a
# request key containing the request method + the actual request.
#
http-method true

# Include HTTP request protocol if found. This will create a
# request key containing the request protocol + the actual request.
#
http-protocol true

# Ignore request's query string.
# i.e.,  www.google.com/page.htm?query => www.google.com/page.htm
#
# Note: Removing the query string can greatly decrease memory
# consumption, especially on timestamped requests.
#
no-query-string false

# Disable IP resolver on terminal output.
#
no-term-resolver false

# Write output to stdout given one of the following formats:
# csv  : A comma-separated values (CSV)
# json : JSON (JavaScript Object Notation)
# html : HTML report
#
#output-format json

# Display real OS names. e.g, Windows XP, Snow Leopard.
#
real-os true

#  Enable IP resolver on HTML|JSON output.
#
with-output-resolver false

# Treat non-standard status code 444 as 404.
#
444-as-404 false

# Add 4xx client errors to the unique visitors count.
#
4xx-to-unique-count false

# Decode double-encoded values.
#
double-decode false

# Ignore crawlers from being counted.
# This will ignore robots listed under browsers.c
# Note that it will count them towards the total
# number of requests, but excluded from any of the panels.
#
ignore-crawlers false

# Ignore parsing and displaying the given panel.
#
#ignore-panel VISITORS
#ignore-panel REQUESTS
#ignore-panel REQUESTS_STATIC
#ignore-panel NOT_FOUND
#ignore-panel HOSTS
#ignore-panel OS
#ignore-panel BROWSERS
#ignore-panel VISIT_TIMES
ignore-panel REFERRERS
#ignore-panel REFERRING_SITES
ignore-panel KEYPHRASES
#ignore-panel GEO_LOCATION
#ignore-panel STATUS_CODES

# Ignore referers from being counted.
# This supports wild cards. For instance,
# '*' matches 0 or more characters (including spaces)
# '?' matches exactly one character
#
#ignore-referer *.domain.com
#ignore-referer ww?.domain.*

# Sort panel on initial load.
# Sort options are separated by comma.
# Options are in the form: PANEL,METRIC,ORDER
#
# Available metrics:
#  BY_HITS
#  BY_VISITORS
#  BY_DATA
#  BY_BW
#  BY_AVGTS
#  BY_CUMTS
#  BY_MAXTS
#  BY_PROT
#  BY_MTHD
# Available orders:
#  ASC
#  DESC
#
#sort-panel VISITORS,BY_DATA,ASC
#sort-panel REQUESTS,BY_HITS,ASC
#sort-panel REQUESTS_STATIC,BY_HITS,ASC
#sort-panel NOT_FOUND,BY_HITS,ASC
#sort-panel HOSTS,BY_HITS,ASC
#sort-panel OS,BY_HITS,ASC
#sort-panel BROWSERS,BY_HITS,ASC
#sort-panel VISIT_TIMES,BY_DATA,DESC
#sort-panel REFERRERS,BY_HITS,ASC
#sort-panel REFERRING_SITES,BY_HITS,ASC
#sort-panel KEYPHRASES,BY_HITS,ASC
#sort-panel GEO_LOCATION,BY_HITS,ASC
#sort-panel STATUS_CODES,BY_HITS,ASC

######################################
# GeoIP Options
# Only if configured with --enable-geoip
######################################

# Standard GeoIP database for less memory usage.
#
#std-geoip false

# Specify path to GeoIP database file. i.e., GeoLiteCity.dat
# .dat file needs to be downloaded from maxmind.com.
#
# For IPv4 City database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
# gunzip GeoLiteCity.dat.gz
#
# For IPv6 City database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
# gunzip GeoLiteCityv6.dat.gz
#
# For IPv6 Country database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
# gunzip GeoIPv6.dat.gz
#
# Note: `geoip-city-data` is an alias of `geoip-database`
#
#geoip-database /usr/local/share/GeoIP/GeoLiteCity.dat

######################################
# Tokyo Cabinet Options
# Only if configured with --enable-tcb=btree
######################################

# GoAccess has the ability to process logs incrementally through the on-disk
# B+Tree database.
#
# It works in the following way:
# - A data set must be persisted first with --keep-db-files, then the same data
#   set can be loaded with --load-from-disk.
# - If new data is passed (piped or through a log file), it will append it to
#   the original data set.
# - To preserve the data at all times, --keep-db-files must be used.
# - If --load-from-disk is used without --keep-db-files, database files will be
#   deleted upon closing the program.

# On-disk B+ Tree
# Persist parsed data into disk. This should be set to
# the first dataset prior to use `load-from-disk`.
# Setting it to false will delete all database files
# when exiting the program.
#keep-db-files true

# On-disk B+ Tree
# Load previously stored data from disk.
# Database files need to exist. See `keep-db-files`.
#load-from-disk false

# On-disk B+ Tree
# Path where the on-disk database files are stored.
# The default value is the /tmp directory.
#
#db-path /tmp

# On-disk B+ Tree
# Set the size in bytes of the extra mapped memory.
# The default value is 0.
#
#xmmap 0

# On-disk B+ Tree
# Max number of leaf nodes to be cached.
# Specifies the maximum number of leaf nodes to be cached.
# If it is not more than 0, the default value is specified.
# The default value is 1024.
#
#cache-lcnum 1024

# On-disk B+ Tree
# Specifies the maximum number of non-leaf nodes to be cached.
# If it is not more than 0, the default value is specified.
# The default value is 512.
#
#cache-ncnum 512

# On-disk B+ Tree
# Specifies the number of members in each leaf page.
# If it is not more than 0, the default value is specified.
# The default value is 128.
#
#tune-lmemb 128

# On-disk B+ Tree
# Specifies the number of members in each non-leaf page.
# If it is not more than 0, the default value is specified.
# The default value is 256.
#
#tune-nmemb 256

# On-disk B+ Tree
# Specifies the number of elements of the bucket array.
# If it is not more than 0, the default value is specified.
# The default value is 32749.
# Suggested size of the bucket array is about from 1 to 4
# times of the number of all pages to be stored.
#
#tune-bnum 32749

# On-disk B+ Tree
# Specifies that each page is compressed with ZLIB|BZ2 encoding.
# Disabled by default.
#
#compression zlib

**Comment by allinurl** [comment]
Please make sure, you are using the right config file. You can use `goaccess -f log -p /path/config/file`.

**Comment by jayprakashstar** [comment]
Yes I am using same. Now it is killing process in middle.

**Comment by allinurl** [comment]
Please open a new issue and specify the problem(s) you are having, and the version of goaccess you are using.

**Comment by LordWingZero** [comment]
Id like to comment to say that its really weird after a fresh install ```goaccess -f logfile.log``` works just fine and shows a GUI for choosing the format but ```cat logfile.log | goaccess``` requires all these config options to be set.

**Comment by allinurl** [comment]
@LordWingZero This is due to the redirect when outputting to a file. So for instance,

    goaccess -f logfile -o json > output.json

If at that point ncurses is initialized, then it will mess up the output. I guess it could check if it's outputting to a file, otherwise display the config file as in the example that you posted. This could be related to #53. Thoughts?

**Comment by benjaoming** [comment]
Tip for this issue: Get a newer version of goaccess. They will at least display non-parseable output so you get a sense of where the issue is.

I got pretty upset when I found out I needed a double space in `%^[%d:%t %^]  "%r"` right after `]`. This was in order to parse a default Nginx configuration on Ubuntu 14.04, I kid you not.

My final work format is:

```
log-format %h %^[%d:%t %^]  "%r" %s %b "%R" "%u" %L
```

**Comment by dms-vkuschev** [comment]
The same problem.
log is:
`[u][05/Oct/2017:00:00:01 +0300] 0.350 0.450 200 188.162.36.133 klubki-v-korzinke.ru GET /category/alize-alize/ HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "http://klubki-v-korzinke.ru/reviews/" 48191 141.8.195.253 klubkivkor
[u][05/Oct/2017:00:00:02 +0300] 0.150 0.200 200 178.215.105.67 klubki-v-korzinke.ru GET /category/prjazha-superwash-alize/?page=2 HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.0.2081 Yowser/2.5 Safari/537.36" "http://klubki-v-korzinke.ru/category/prjazha-superwash-alize/" 19301 141.8.195.253 klubkivkor`
What log-format i must use?

**Comment by allinurl** [comment]
@dms-vkuschev Can you please describe the fields in your log format?

**Comment by nad2000** [comment]
I ran into the same issue. My .goaccessrc:

```
time-format %T
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D
```

When I ran `goaccess access_log -o report.html`, I got:

> GoAccess - version 1.2 - Mar  7 2017 06:40:58
> Config file: /etc/goaccess.conf
> 
> Fatal error has occurred
> Error occured at: src/parser.c - parse_log - 2705
> No time format was found on your conf file.

I also tried with `time-format %H:%M:%S`...


When I ran `goaccess access_log` and entered the same format string in dialog, everything works fine :(
Any ideas what could be wrong?

**Comment by benjaoming** [comment]
@nad2000 Where are your logs from? See my post right above about the double space?

**Comment by nad2000** [comment]
@benjaoming , my bad, well, in a way. I was operating under the assumption that the user configuration in the home directory (`~/.goaccessrc`) overrides the default one seamlessly by default. I reckon it was a reasonable assumption. It turns out it should be given explicitly using **`-p/--config-file=<filename>`** (Custom configuration file). Running `goaccess access_log -o report.html -p ~/.goaccessrc` **SOLVED** the issue.

**Comment by allinurl** [comment]
@nad2000 I think this issue was fixed upstream. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test this out. Thanks!

**Comment by omidraha** [comment]
Worked for me:

`$ goaccess -f nginx.log  --log-format="%h %^[%d:%^] \"%r\" %s %b \"%R\" \"%u\""   --date-format="%d/%b/%Y"  --time-format="%T"  -a > report.html
`
