### ISSUE TITLE
The only way to avoid the dialog...

### ISSUE THREAD

**Issue by jidanni** [allinurl/goaccess#1361]
ne would think a
```
$ cat ~/.goaccess
log-format %h %^[%d:%t %^] "%r" %s %b
```
file would be read. But in fact it is not.

One still enters the quiz dialog.

One would also think
```
$ goaccess --no-global-config -p ~/.goaccessrc /tmp/access.log.2019-01-18
```
would get it read. It does not.

The only way to avoid the dialog turns out to be
```
$ goaccess --log-format=COMBINED /tmp/access.log.2019-01-18
```
(Seen on Debian.)

**Comment by jidanni** [comment]
Oops... one moment please.

**Comment by allinurl** [comment]
If all you got in your ~/.goaccessrc is `log-format`, then you also need `date-format` and `time-format`. `--log-format=COMBINED` works since it assumes you in fact are using a combined log format. 

I guess a possible solution would be to compare a custom log-format to one of the pre-defined and use the relevant time/date-format.
