### ISSUE TITLE
goaccess-tcb update to 1.3 not working

### ISSUE THREAD

**Issue by rctgamer3** [allinurl/goaccess#1366]
Latest version available is still 1.2

**Comment by rctgamer3** [comment]
Running Debian stretch, somehow apt still reports 1.2 as the latest version, however I can see that 1.3 is on the repo.

**Comment by rctgamer3** [comment]
```
# dpkg -i goaccess-tcb_1.3_amd64.deb
dpkg: warning: downgrading goaccess-tcb from 2:1.2 to 1:1.3
(Reading database ... 12345 files and directories currently installed.)
Preparing to unpack goaccess-tcb_1.3_amd64.deb ...
Unpacking goaccess-tcb (1:1.3) over (2:1.2) ...
Setting up goaccess-tcb (1:1.3) ...
Processing triggers for man-db (2.7.6.1-2) ...
```

**Comment by allinurl** [comment]
[**v1.4**](https://goaccess.io/download) is out! Available as well in the deb repo for the following distributions: 

```
goaccess |  1:1.4-xenial |  xenial | amd64, i386
goaccess |  1:1.4-bionic |  bionic | amd64
goaccess |    1:1.4-eoan |    eoan | amd64
goaccess |   1:1.4-focal |   focal | amd64
goaccess | 1:1.4-stretch | stretch | amd64, i386
goaccess |  1:1.4-buster |  buster | amd64, i386
```
If you get a `GPG error The following signatures couldn't be verified because the public key is not available.` Please make sure to download the new public key as shown [**here**](https://goaccess.io/download#official-repo) above to correct this.
