### ISSUE TITLE
it has been running with large log file 

### ISSUE THREAD

**Issue by xingjianhui** [allinurl/goaccess#1387]
* 80 millions lines nginx log file (30G)
* version: 1.3
* save on memory
1. confiuration:
 ``` ./configure --enable-utf8 && make && make install ```
2. command: goaccess -a -r 
3. it out of memory kill by system when feeding 8 millions logs 
* save on disk
1. confiuration:
```
   ./configure --enable-utf8 \
      --enable-geoip=legacy  \
      --bindir=/usr/bin \
      --sysconfdir=/etc \
     --enable-tcb=btree 
   make & make install 
```
2. command: goaccess -a -r 
3. it has been working (4days 20h) 
```Parsing... [26,054,204] [63/s]```

thanks

**Comment by allinurl** [comment]
Do you have enough memory on the machine? I'd recommend trying the default storage (hash tables).

FWIW, here's a quick test on a 100M log (w/o `-a`). 

![goaccess-100m](https://cloud.githubusercontent.com/assets/5005367/20352065/7bdfb75a-abdb-11e6-8d66-36f703658929.png)

1. Use `-g` to use the standard GeoIP database for less memory usage (if using geolocation). 
2. Use `-q` to strip the request's query string. If you have a lot of timestamped requests, and you don't need these on the report, then this flag would help. 
3. Do you need all panels? Otherwise, you could disable some of them on the config file. Panels that consume most of the ram are `REQUESTS`, `REQUESTS_STATIC`, `NOT_FOUND`, `REFERRERS`.
4. Avoid using `-a` since it will store every user agent a host has.

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

[**v1.4**](https://goaccess.io/download) has been released.
