### ISSUE TITLE
Missing space in error output for invalid request protocol

### ISSUE THREAD

**Issue by JamesSkemp** [allinurl/goaccess#1472]
With GoAccess 1.3 (Ubuntu via Windows Subsystem for Linux, built from release), I'm parsing W3C logs (converted from IIS) with the following:

    goaccess /path/to/log.log
        --log-format="%d %t %m %U %q %e %h %H %u %R %s %b %L"
        --date-format="%Y-%m-%d"
        --time-format="%H:%M:%S" -a -o /path/to/report.html

I'm getting the following error message in the console:

> Parsed 1 linesproducing the following errors:
> Token '-' doesn't match specifier '%H'
> Format Errors - Verify your log/date/time format

I know the issue is with the logs themselves - it appears IIS wasn't logging the cs-version and was using it's standard for empty/null, a `-`, which GoAccess treats as non-empty.

The minor issue is that there should be a space between "lines" and "producing" in the error message.

Current:
> Parsed 1 **linesproducing** the following errors:

Fixed:
> Parsed 1 **lines producing** the following errors:

**Comment by allinurl** [comment]
Thanks for reporting this. It has been fixed per this [https://github.com/allinurl/goaccess/commit/71c624a3adfe2a4d664c6fbcfca7ed736d5a2272#diff-bfbbcdf73459e9ea8fb4afa8455ce74d](https://github.com/allinurl/goaccess/commit/71c624a3adfe2a4d664c6fbcfca7ed736d5a2272#diff-bfbbcdf73459e9ea8fb4afa8455ce74d). It will be fixed in the upcoming release, otherwise, feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).
