### ISSUE TITLE
Each run is re-adding log data from all previous runs

### ISSUE THREAD

**Issue by ChrisWiegman** [allinurl/goaccess#1617]
My command looks something like the following:

`goaccess /var/log/nginx/access.log -a --keep-db-files -o /var/www/analytics/index.html --log-format=COMBINED --load-from-disk --db-path=/var/goaccess/www`

It runs on, successfully, on a cron at whatever schedule. The issue is that it is fully parsing the log with each subsequent run rather that just new data. For example, if I have, say 1000 visitors and run it 5 times it will accurately show the 1,000 visitors on the first run. On the 2nd it will show 2,000, on the third it will show 3,000 and so on. 

Here's an example log line for reference:

`111.111.111.111 - - [30/Nov/2019:15:32:18 +0000] "GET /favicon.ico HTTP/2.0" 200 5430 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"`

Is there something I'm missing somewhere with the config?

**Comment by allinurl** [comment]
Great question and this is part of a long conversation. Please take a look at this [**workaround**](https://github.com/allinurl/goaccess/issues/334#issuecomment-307569697). However, note that since the on-disk storage is being replaced with a different solution, the current workaround won't work going forward.

**Comment by ChrisWiegman** [comment]
This gets me a start. Thanks!

**Comment by allinurl** [comment]
Closing this as it is a dup. Feel free to reopen it if needed.
