### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by shibumi** [allinurl/goaccess#1763]
Hi,
the last release is from 2018, is it possible to tag a new "stable" release for distributing it to the users on major distributions?

**Comment by allinurl** [comment]
Thanks for the heads up. This release was certainly delayed. I plan to release v1.4 next Monday. May 18, 2020. Stay tuned!

**Comment by shibumi** [comment]
@allinurl wow, awesome!! thank you so much.

**Comment by allinurl** [comment]
[**v1.4**](https://goaccess.io/download) is out! Available as well in the deb repo for the following distributions: 

```
goaccess |  1:1.4-xenial |  xenial | amd64, i386
goaccess |  1:1.4-bionic |  bionic | amd64
goaccess |    1:1.4-eoan |    eoan | amd64
goaccess |   1:1.4-focal |   focal | amd64
goaccess | 1:1.4-stretch | stretch | amd64, i386
goaccess |  1:1.4-buster |  buster | amd64, i386
```
If you get a `GPG error The following signatures couldn't be verified because the public key is not available.` Please make sure to download the new public key as shown [**here**](https://goaccess.io/download#official-repo) above to correct this.

**Comment by shibumi** [comment]
@allinurl Nice! I will update the official package on Arch Linux, too :)
