### ISSUE TITLE
Squid parsing

### ISSUE THREAD

**Issue by CryoRig** [allinurl/goaccess#1924]
i would like to use goaccess for our squid server but i just can't figure out how to configure the settings for Date / Time / Logformat 

our log looks like this:
`1600825263.965 [23/Sep/2020:03:41:03 +0200] 245 00.00.00.00 00.00.00.00 - CONNECT login.microsoftonline.com:443 HTTP/1.1 - 200 5809 TCP_TUNNEL ROUNDROBIN_PARENT/squiddmz -`

the logconfig for squid itself:
`%ts.%tu [%tl] %tr %>a %{X-Forwarded-For}>h %ui %rm %ru HTTP/%rv %mt %>Hs %<st %Ss %Sh/%<A %<pt`

Anyone willing to help?

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`date-format %d/%b/%Y`
`time-format %H:%M:%S` or in same way `time-format %T`
`log-format %^ [%d:%t %^] %L %h %^- %m %U %H %^ %s %b  %^`

or in command-line:
`--date-format='...' --time-format='...' --log-format='...'`

**notes:**
I hope than `IPs` be only example because the value `00.00.00.00` isn't not valid.
It will be so difficult parser this log.
I supposed that field `%ui` is ever `-` because is preceded for by field `X-Forwarded-For (XFF)` with variable # of words.
If isn't the case please change by `... "%{X-Forwarded-For}>h" ...`

**Comment by CryoRig** [comment]
This works perfect, thanks

**Comment by b-tin** [comment]
```
1661337089.962 [24/Aug/2022:10:31:29 +0000] 91 172.16.16.77 - - GET http://detectportal.firefox.com/success.txt? HTTP/1.1 text/plain 200 367 TCP_MISS HIER_DIRECT/detectportal.firefox.com 45
```

sorry to disturb this thread, i've a similar squid-log format but not work :( could pls help me take alook, i've tried a lot but still fail

```
> goaccess -f access.log --date-format='%d/%b/%Y' --time-format='%H:%M:%S' --log-format='%^ [%d:%t %^] %L %h %^- %m %U %H %^ %s %b %^'
==96605== GoAccess - version 1.6.2 - Jul 16 2022 02:44:06
==96605== Config file: /opt/homebrew/Cellar/goaccess/1.6.2/etc/goaccess/goaccess.conf
==96605== https://goaccess.io - <hello@goaccess.io>
==96605== Released under the MIT License.
==96605==
==96605== FILE: access.log
==96605== Parsed 1 lines producing the following errors:
==96605==
==96605== Token '-' doesn't match specifier '%m'
==96605==
==96605== Format Errors - Verify your log/date/time format
Cleaning up resources...
```

**Comment by allinurl** [comment]
@b-tin This should do it (assuming spaces as delimiters):

    goaccess squid.log --log-format='%^ [%x] %L %h %^ %^ %m %U %H %M %s %b %^_%C %^/%v %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --date-spec=min --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES
