### ISSUE TITLE
Doesn´t add up

### ISSUE THREAD

**Issue by tellustheguru** [allinurl/goaccess#1963]
After I Upgraded Goaccess to 4.1.1 the statistic look very strange:

<img width="788" alt="bild" src="https://user-images.githubusercontent.com/47452862/99128144-5d31b800-260a-11eb-933f-28bd58b655de.png">

<img width="961" alt="bild" src="https://user-images.githubusercontent.com/47452862/99128297-bbf73180-260a-11eb-8b2c-691c970688b8.png">

**Comment by allinurl** [comment]
Could you please describe what you mean with `statistic look very strange`? e.g., data-wise, numbers wrong, user interface? Thanks

**Comment by tellustheguru** [comment]
I will try to explain what does not go together. If you look at the screenshot, I have received 13,493,850 hits in about a month, it does not get even in a year. If you look at exclusive hits, it is usually around 2000 hits.

To rule out if I had been attacked, I looked at the section ipadress and hostname, where it does not coincide with the total value of the summary.

Now I have gone back to version 1.4, where admittedly a bug means that I have to restart goaccess every day to get goaccess to read the new log file after rotation.

(translated from swedish in google translate)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl

I believe it is the problem in identifying that the file has been rotated and therefore it is now a new one.
Perhaps `GOACCESS` should be reprocessing the entire file, similarly to what happened to me in real-time.

My question: He quotes "where admittedly a bug means that I have to restart ..." -- So he is running in real-time?

Solution: upgrade to version 1.4.2

**Comment by tellustheguru** [comment]
@0bi-w6n-K3nobi 

Yes, I´m run goaccess in realtime.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @tellustheguru 

My problem is described in issue #1958.
But, it is very long and has other subjects as well.

@allinurl fix it in patch a43993b.
The problem occurs if you are using **more than** (one) 1 `LOG`.
So, you will need to compile from upstream or upgrade to version 1.4.2

**Comment by allinurl** [comment]
@tellustheguru question for you, did you use either `--restore` or `--persist`? I ask because there was an issue with the overall count when attempting to restore from disk which was fixed on v1.4.1. Please upgrade to v1.4.2 for accurate counting **BUT** you will need to delete your old database files and parse your logs form scratch.

Also, just so I understand better your concern. the 13,493,850 hits, is that what you are comparing against the total in the IP panel? I can't see that total so I'm not sure where the issue is exactly. 

From what I can see, looks like you got a few visitors that are hitting your server a lot. I'm not sure what kind of traffic you have so is hard for me to judge, but you could correlate some data, for instance, first IP on the list has visited you only 6 times in one month and has generated that amount of hits to your server/website. So it does look like a bot, but again, hard to say not know the type of website you offer.

**Comment by andreychirikba** [comment]
Not sure if original poster meant the same, but I also notice that the totals (e.g. total Visitors in UNIQUE VISITORS PER DAY - INCLUDING SPIDERS) are a sum of unique visitors per day. This may very well be (and mostly surely are) the same visitors day-to-day, but are counted as unique for the whole period by adding uniques from every day. Same goes for other metrics.

**Comment by allinurl** [comment]
Sorry, I guess I'm not seeing the issue here. Should the total Visitors on that panel be different than the sum of unique visitors per day? Thanks.

**Comment by andreychirikba** [comment]
@allinurl, if every day there are different unique visitors then it would be correct. But imagine that every day the visitors are almost the same (true in my case, e.g.): then unique visitors per day are correct, but if you just sum them up for a month total, then the total won't make sense. Because in reality it's all the same visitors every day, so number of unique visitors per month should be almost the same as per day.

**Comment by allinurl** [comment]
@andreychirikba I see and thanks for expanding on that. Currently the way the visitors count works is by generating a unique key composed of IP/date/UA. So the overall count essentially is the summation of each date unique count. This hasn't changed since early versions of goaccess so like you said, I'm not sure if the original poster meant that? BTW, [here](https://github.com/allinurl/goaccess/issues/1777#issuecomment-631002889) are some additional notes on this.

However, you could also get a 'more' unique count by looking at the "VISITOR HOSTNAMES AND IPS" panel, which should give you a better sense of actual unique IPs. #117 will add filters, allowing you to see the stats for a given period of time. 

Other than that, I don't know if there's a way to keep track of recurring visitors without getting into cookies/sessions. Any feedback/ideas are always welcome :)

**Comment by tellustheguru** [comment]
I upgraded to 1.4.3 it is now working.
