### ISSUE TITLE
Syslog date format

### ISSUE THREAD

**Issue by bellegarde-c** [allinurl/goaccess#1975]
For a custom log (syslog), I need to parse this two lines:
```
Nov 22 11:11:57 srv-data-1 srv-data-1: f20d801z smb://srv-data-1/profils 172.11.164.78
Dec  2 11:16:57 srv-data-2 srv-data-2: dacauin-c smb://srv-data-2/home 172.11.66.50
```
My log format:
`--log-format='%d %t %v %^: %e %U %h' --date-format='%b %d' --time-format='%H:%M:%S'`

Was working in November but fails now because of two spaces between Dec and 2.

Can't find a solution.

**Comment by bellegarde-c** [comment]
Workaround:
`tail -f /var/log/goaccess_data.log | tr -s " " | goaccess`

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @bellegarde-c 
Hi @allinurl 

Could we implement it like `strftime`?
In this way, the field should be declared like **`%_d`** instead of `%d`.

See you.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @bellegarde-c 

For now, you can execute follow command like workaround:
```
sed 's@^\(...\)\s\s@\1 @g' LOGFILE  ...
```
It will be change 2 spaces for 1, between the month and the day field.

I hope I've helped.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

As I said earlier, on some of the issues that I no longer remember.
In the panel `Unique visitors per day`, I have seen weird behaviour, for requests above ...
![image](https://user-images.githubusercontent.com/71027865/100935018-53df9100-34ce-11eb-8e59-d7fc5eb3e38c.png)
and whatever if I use `--date-spec=hr` or `--date-spec=date`.

Again, I believe that cause is year missing into date field.

In the panel `Time Distribution` have 2 `HITS`/`VISITORS` in unique point.
![image](https://user-images.githubusercontent.com/71027865/100936330-1976f380-34d0-11eb-8552-3e627bb7cb95.png)

See You.

**Comment by allinurl** [comment]
Thanks for posting a possible workaround. @0bi-w6n-K3nobi yeah, I think we could do something like `strftime`. Please keep this open so I don't forget to look into it.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi BTW, the screenshot you posted, is that in the latest version? Could you please test this on the terminal output and see if you're getting the same result? Thanks

**Comment by bellegarde-c** [comment]
Tried to play with tr -s " ", stdbuf... Worked but fails to make this working as a systemd service;

BTW, just changed my rsyslog conf for a parsable output (YYYY-MM-DD)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @bellegarde-c 

Scripted syntax and tokenization are difficult and complex into shell.
SystemD is even more sensitive.
I even had to use external script due to the token.

You can try some combinations before the external script:
`tr -s \" \"`
`tr -s \"\ \"`
`tr -s \\" \\"`
`tr -s \\"\\ \\"`

and so...

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

Yeah, It is latest version.
There is actually some difference when I use `--date-spec=date` or `--date-spec=hr` :

![image](https://user-images.githubusercontent.com/71027865/101023040-f93b4900-3550-11eb-9052-e02974e4230b.png)

In the panel `Time Distribution` change point value from `11` to `11:1`.

Into `terminal` I see, with `date`and `hr` respectively:

![image](https://user-images.githubusercontent.com/71027865/101024428-d873f300-3552-11eb-8a25-18ca8a5c12ca.png)

But everything is OK if I change the filter added the year, to:

**Comment by allinurl** [comment]
I pushed a commit https://github.com/allinurl/goaccess/commit/6bcc639b98d8f956a23a5907b02a81183354f1db that should address this. It should work by just doing what you have there:

    goaccess syslog.log --log-format='%d %t %v %^: %e %U %h' --date-format='%b %d' --time-format='%H:%M:%S'

It also ensures to output the missing year. Feel free to let me know how it works for you. I plan to push it out in a minor release.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi I think it will address the issue you mentioned in your last post. Let me know. Thanks
