### ISSUE TITLE
Issue concerning logformat in newer versions

### ISSUE THREAD

**Issue by overnine** [allinurl/goaccess#202]
When using both the major release of 0.8.5 and a compile directly from github i seem to encounter an invalid Log format for S3 Logs, while i have previously used the logformat without problems (and it's also the format which pops up on google when googling "goaccess s3").

It seems to simply not work in later versions of goaccess, below is two outputs, both tests uses the same files as seen in the test with 0.8.5:

0.8.5 run: https://gist.github.com/overnine/78ae830097aeccb5fb00
0.8.1 run: https://gist.github.com/overnine/74b52d657d109214ffaf

**Comment by allinurl** [comment]
I downloaded your sample log and it did work for me on 0.8.5. However, one thing to note is that the latest version does not count 4xx as unique visitors, so you may want to use `--4xx-to-unique-count`. Also I'd recommend using the latest config [file](https://raw.githubusercontent.com/allinurl/goaccess/master/config/goaccess.conf) since some features are taken from there.

    goaccess -f log -p ~/.goaccessrc

Here's the log format I tried as well:

    log-format %^ %^ [%d:%^] %h %^ %^ %^ %^ "%r" %s %^ %b %^ %^ %^ %^ %^ "%u"

Let me know how it goes. Thanks.

**Comment by overnine** [comment]
Okay, my issue probably was due to something else, thanks for your time!

**Comment by overnine** [comment]
Might have been solved by stripping initial whitespace/newlines as described in #203
