### ISSUE TITLE
Non-GNU Linux systems are mislabeled as GNU+Linux recently

### ISSUE THREAD

**Issue by dertuxmalwieder** [allinurl/goaccess#2075]
In 2e15d8ef21edc5952ba6ba3ad321b5976a165861, several pull requests from @throwaway1037 were merged which included renaming "Linux" to "GNU+Linux". Now that would mean that all Linux systems which are detected are GNU systems instead of (e.g.) Busybox-based Linuces, like Tiny Core Linux and Alpine Linux.

As there is no safe way to detect these libc-related differences, the commit - in opposite to what it *should* have done - has made the OS detection **less** correct under some circumstances, because all Linux systems use the Linux kernel, but not all Linux systems use the GNU userland.

I suggest to undo this part of the commit.

**Comment by throwaway1037** [comment]
The subtle problem with this is that there are also GNU distributions which are not Linux, eg. Debian GNU+kFreeBSD, GNU Guix (HURDedition), Arch GNU+HURD, and even GNU+NT using Cygwin or mingw.

In the vast majority of cases, distributions which use the Linux kernel are also GNU; hence I would recommend undoing `ea88757`.

I don't know if there is a robust way to detect where the system is GNU or not, aside from listing all the Unix-like operating systems, but specifying GNU+Linux or BusyBox+Uboot+musl+Linux, etc... for the other distributions.

**Comment by dertuxmalwieder** [comment]
> The subtle problem with this is that there are also GNU distributions which are not Linux, eg. Debian GNU+kFreeBSD, GNU Guix (HURD edition), Arch GNU+HURD, and even GNU+NT using Cygwin or mingw.

There is no problem with that, as they are not detected as Linux anyway.

> In the vast majority of cases, distributions which use the Linux kernel are also GNU

100 percent of Linux systems are Linux systems.
Less than 100 percent of Linux systems are GNU systems.

Hence, Linux is a more correct label than GNU+Linux.

> Systems which use Linux but not GNU are an exceedingly tiny edge case (eg. Tiny Core, Alpine) 

Where can I find reliable statistics about that?

> I would recommend adding such non-GNU systems which use Linux as explicitly listed exceptions, and assume GNU+Linux as a sane default.

I would recommend adding all GNU systems which are the only ones to be named “GNU+Linux” instead. That would be easier as they’re easy to find.

By the way, what about Void Linux which is available in a musl and a glibc version? “Perhaps-GNU+Linux”? Honestly, you cannot safely tell from a web server log whether you have a GNU or a non-GNU system on the other side. It’s probably better to keep software politics out of this project.

**Comment by throwaway1037** [comment]
> 100 percent of Linux systems are Linux systems.
Less than 100 percent of Linux systems are GNU systems.

"Linux systems" are most often actually GNU+Linux. It is incorrect to refer to these systems as "Linux systems".

> Where can I find reliable statistics about that?

Use common sense. Do you seriously think two tiny, niche distros such as Tiny Core and Apline are actually used by more than a small community of people, let alone more popular than the Debian GNU+Linux family, the Red Hat GNU+Linux family, and the Arch GNU+Linux family, etc... combined?

> I would recommend adding all GNU systems which are the only ones to be named “GNU+Linux” instead. That would be easier as they’re easy to find.

On the contrary, most distributions using the Linux kernel are GNU+Linux, whereas you can only really find Tiny Core and Alpine as examples of non-GNU systems using the Linux kernel. Therefore, systems using Linux as a kernel, but not GNU as the rest of the operating system are the exception, not the rule. (Technichally, the Android family of systems counts, but is irrelevant here because it is detected separately.)

> By the way, what about Void Linux which is available in a musl and a glibc version? “Perhaps-GNU+Linux”?

Void GNU+Linux is still GNU+Linux because the system is still GNU with Linux added; swapping out glibc for musl only swaps out a tiny component of GNU so it's not really worth reflecting it in the name of the system, as it is not a major component, at least in my opinion.

We could list Void as an exception to be either GNU+Linux or GNU+Linux+musl.

> Honestly, you cannot safely tell from a web server log whether you have a GNU or a non-GNU system on the other side.

We know; that's the problem here. It's probably a good thing too, to help lessen tracking and surveillance on the web.

> It’s probably better to keep software politics out of this project.

To quote RMS, "You can leave politics alone, but politics won't leave you alone."

Software always has been, is, and will be political; that's just the world we live in.

However, I don't understand how politics are relevant to this issue; it concerns detecting GNU and Linux, not governmental policies.

**Comment by dertuxmalwieder** [comment]
> "Linux systems" are most often actually GNU+Linux. It is incorrect to refer to these systems as "Linux systems".

Busybox Linux systems are rarely GNU+Linux systems. It is incorrect to refer to these systems as "GNU+Linux".

> Use common sense.

Common sense tells me that the only common denominator of systems which use the Linux kernel is "Linux", not "GNU".

> On the contrary, most distributions using the Linux kernel are GNU+Linux

"Most", exactly. And I don't want my website statistics to be **almost** correct.

> We know; that's the problem here. 

Which is not a problem unless you add a userland component to the only detected part of a Linux-based operating system: the Linux kernel. Which is why adding "GNU+" is wrong.

> To quote RMS, "You can leave politics alone, but politics won't leave you alone."

Quoting RMS is exactly the problem here. The whole "BUT IT'S GNU!" issue is a very philosophical/political discussion. GoAccess, however, is in its entirety a technical project which has the goal to show **collected** data in a more accessible way. As web servers don't **collect** whether a client is GNU or not, you cannot show "GNU" reliably, so you should not do that.

>  it concerns detecting GNU and Linux, not governmental policies.

You cannot detect GNU from web server logs. Don't add your personal opinion of which operating system a client runs to a project which only processes actual data.

**Comment by throwaway1037** [comment]
> Busybox Linux systems are rarely GNU+Linux systems. It is incorrect to refer to these systems as "GNU+Linux".

> Common sense tells me that the only common denominator of systems which use the Linux kernel is "Linux", not "GNU".

True, but as I mentioned, these systems are the exception, not the rule. The same default is GNU+Linux because that's what most systems are.

The common denominator does not dictate the name of the system.

> "Most", exactly. And I don't want my website statistics to be almost correct.

Your statistics will be more correct assuming GNU+Linux as a sane default because non-GNU distros are barely used, and when they are they are for small systems, not systems with full-blown web browsers that are logged and showed in tools like goaccess.

> Which is not a problem unless you add a userland component to the only detected part of a Linux-based operating system: the Linux kernel. Which is why adding "GNU+" is wrong.

Your statement is incorrect.

1. GNU is not a "userland component"; it is what makes up most of the system. GRUB, the GNU coreutils, GCC, glibc, gdb, and other vital system components are part of the GNU Project.
2. The system is not "Linux-based" or a "Linux system". No such systems exist. Linux is ***just a kernel***. Systems are made up of many, many more components and as such have other names, such as BusyBox+musl+Linux.
3. Referring to a system which is GNU with Linux added as "GNU+Linux" is correct.

> Quoting RMS is exactly the problem here. The whole "BUT IT'S GNU!" issue is a very philosophical/political discussion.

In this context, it's a technichal issue; the system is undeniably GNU with Linux added, hence the correct name is GNU+Linux. Regardless of your philosophical or political views, it is impossible to deny this fact.

> GoAccess, however, is in its entirety a technical project which has the goal to show collected data in a more accessible way.

See above.

> As web servers don't collect whether a client is GNU or not, you cannot show "GNU" reliably, so you should not do that.

You can. We can detect the name of the system as goaccess already does.

Again, non-GNU systems which use Linux, such as BusyBox+musl+Linux are exceptions, not the rule.

> You cannot detect GNU from web server logs.

Goaccess already does; at least it detects the name of the system and coreectly classifies the system as a GNU+Linux distribution.

> Don't add your personal opinion of which operating system a client runs to a project which only processes actual data.

Ironically, your argument is hinged on literally two exceptions to the rule. Your opinions seem to be hinged on bias against GNU. I can only presume you intend to bury GNU under the meme that the entire system is "Linux".

Goaccess processes data about which system is which, and overriding 99.9% of distros for the cases in which two non-GNU distros are used is silly.

**Comment by dertuxmalwieder** [comment]
> these systems are the exception, not the rule. 

And they should **not** be misrepresented in accurate statistics.

> Linux is just a kernel. 

And you can **not** safely detect anything else from your web server logs.

> Referring to a system which is GNU with Linux added as "GNU+Linux" is correct.

Which the code already does by sorting distributions which are GNU as “GNU+Linux”. You can not make any safe assumptions about other Linux-based systems.

> Again, non-GNU systems which use Linux, such as BusyBox+musl+Linux are exceptions, not the rule.

Name your source.

Also, that would still not fix the problem that your proposed changes would incorrectly put the GNU label on some non-GNU systems. RMS would not like that either.

> Goaccess already does; at least it detects the name of the system and correctly classifies the system as a GNU+Linux distribution.

Which is why the current version of the code is as precise as you can get.

> Ironically, your argument is hinged on literally two exceptions to the rule.

Which makes the rule wrong. The only thing you can agree on by just reading the logs is the kernel.

> overriding 99.9% of distros for the cases in which two non-GNU distros are used is silly.

Show me a way to safely detect GNU from reading the web server logs (also consider LFS and Gentoo here) and I’ll gladly accept your suggestions. Until then, please stop replacing “I’m 100% sure that this uses the Linux kernel” by “I’m almost sure that this could be a GNU system”. I want my statistics to be correct, not to be probably correct.

**Comment by throwaway1037** [comment]
#2077 should be a suitable resolution for both of us.
