### ISSUE TITLE
arm64 @ https://deb.goaccess.io/

### ISSUE THREAD

**Issue by by** [allinurl/goaccess#2295]
Any plans to also provide an arm64 package at https://deb.goaccess.io/, ideally for buster? – Thanks!

**Comment by allinurl** [comment]
I'd like to add an arm64 package to the repo. There's a conversation under #1894, like I mentioned there, I'm looking for an automated way of building this package. Please feel free to chime in if you know a good way of doing this. Thanks

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

Do you already have the same one for `x86_64`?

I have tested it in `LXC`, and I believe it is also valid for `LXD`.
If you already have the process for `x86_64`, even in Docker, 
I think the same process can be done for `ARM64/AARCH64`.

It is only necessary to build the same Docker/`LXC`/`LXD` on `ARM64`.
`QEMU` will do the rest of the work, allowing Docker to run as if it were native `x86_64`.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Thanks for the input. Currently I just spin up multiple distros using vagrant and build accordingly. I'd like to give DistroBuilder a shot. I'm curious, are you able to build an arm64 goaccess package from [source](https://github.com/allinurl/goaccess#build-from-release) on your end?

**Comment by 0bi-w6n-K3nobi** [comment]
@allinurl 

Yeah... I believe that is possible too with using vagrant to arm64 arch.
I'm not familiar with vagrant... but if you have a example I will can try build for `ARM64`/`AARCH64` too.

As you already know, I using Fedora and I didn't have problem for build at `ARM`/`ARM64` arch.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl

I'm researching for best and easy way to you make it .
Well... `Valgrand` can use `VirtualBox`, `KVM` or `Docker` containers under Linux.
I believe that better way is using `Docker` directly.
And so do you will need one for each OS and each architecture.
For that, `DOCKER` have the `--platform` parameter.
I think it will be need `QEMU` for that.
One great and simple tutorial about this you can find [here](https://www.docker.com/blog/multi-platform-docker-builds/).

**Note 1:**
Personally, I don't like `DOCKER`. 
It's Ok for App deployment under Server.
But, it's very confuse and bit more that necessary at network stack.
If you use directly changes under `IPTables`, and need reload, so need too restart all `DOCKER` Service. 
It's a big fault for me.

Humm... Under certain circumstances, using `LibVirtd` stack, the same can be ocurr for `LXC`.
But, using `LXC-Net` stack You can restart `IPTables` at any time!

**Note 2:**
One other great tool is [Singularity](https://sylabs.io/singularity/).
And there an article [Singulary vs Docker](https://pythonspeed.com/articles/containers-filesystem-data-processing/), comparing both.
This one make what should it do: turn `DOCKER` one advanced `CHROOT` with simplicity.
I don't know that will running at foreign arch...

**Note 3:**
Also take a look at the [podman](https://podman.io/) tool.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

Just a test that made here!

`singularity pull docker://quay.io/fedora/fedora:35-aarch64`
`./fedora_35-aarch64.sif`
`Singularity> cat /etc/os-release  | grep PRETTY_NAME`
**`PRETTY_NAME="Fedora Linux 35 (Container Image)"`**
`Singularity> arch`
**`aarch64`**
`Singularity> uname -a`
**`Linux XXX-XXX  5.16.18-200.fc35.x86_64 #1 SMP PREEMPT Mon Mar 28 14:10:07 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`**

Nice! Do you need only adjust your `DOCKER` with necessary packages.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Thank you for sharing these findinds. It's very nice, let me give this a shot and I'll post back, sounds like this will be the way to go :)

**Comment by allinurl** [comment]
I just noticed [azure added arm64 support](https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/), hopefully they will add it to github actions.

**Comment by allinurl** [comment]
Folks, goaccess is now available in the deb repo for arm64.

```
goaccess |    1:1.5.7-jammy |    jammy | arm64, amd64
goaccess |   1:1.5.7-impish |   impish | amd64
goaccess |   1:1.5.7-bionic |   bionic | arm64, amd64
goaccess |    1:1.5.7-focal |    focal | arm64
goaccess |  1:1.5.7-stretch |  stretch | amd64, i386
goaccess |  1:1.5.7-hirsute |  hirsute | amd64
goaccess |   2:1.5.7-buster |   buster | arm64, amd64
goaccess | 1:1.5.7-bullseye | bullseye | amd64
```

Closing this. Feel free to reopen it if needed.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

Interesting... 
How to build that? Do you use `DOCKER` only? or `Singularity`?
Can you speak about  cake recipe?

Maybe be interesting build others, like that Fedora, CentOS 7 and Ubuntu.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi good question, for debian buster, I used qemu and their cloud image, fairly easy and straightforward. For ubuntu, it seems like you need to use some yml files to login so I found it to be much harder than it needed to be so I ended up using docker arm64v8/ubuntu images which turned out to me much easier. For the next build, I'll have some scripts to automate this process. 

I do appreciate you posting those guides as they really helped me make those decisions. I already see several arm64 downloads :)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

I think that we are at right way.
Although I prefer `Singularity` tool rather to `DOCKER`, I believe that last one are good enough.
After build it with all tools including the compiler, nothing more will need besides map/mount the source dir from host.

As you already mentioned, Debian distro it won't be a problem.
Unbuntu too, whose `DOCKER`s are found at `dockerhub`.
Fedora are found at `quay.io`, like I already told above.
I won't even mention Alpine Linux.
The problem will be another that are not found a base `DOCKER`, like ArchArm Distro.
I like very much Arch Linux and so ArchArm. I belive that is a great distro for Arm after Debian derivate like Armbian and Ubuntu.

I found some docs for build `DOCKER` for ArchArm.
But, besides the `DOCKER` is necessary create and document the process for build `GOACCESS` package for each OS distro.

I have good experience for  build for Fedora and Suse.
And I "make do with" for Arch, Alpine and Debian.

Well, I will so busy at next weeks.
But... I would be very happy to build guides for that, since build `DOCKER` until files/scripts for generate `GOACCESS` package for each OS Distro.

And... I hope to talk you soon as possible.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi I agree. Singularity seems easier to work with, especially with filesystems as the [guide](https://pythonspeed.com/articles/containers-filesystem-data-processing/) you posted mentions. Thanks for sharing that, I'll be taking a look in more detail.
