### ISSUE TITLE
Auto Refresh/page reload HTML report

### ISSUE THREAD

**Issue by radim-ek** [allinurl/goaccess#2305]
I can't use a websocket. So I do a cron with minute loop.
But now I need to manualy refresh a page. Please add options to auto refresh webpage html maybe via meta…

`--http-meta-refresh=XX`

And in HTML will be generated
`<meta http-equiv="refresh" content="XX">`

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @radim-ek 

I try understand that you need... But that won't work as you want.
Either you use real-time with `WebSocket` or you will just have a final report.

It is not possible to have a report in real-time just by adding a refresh to the page,
because it is not "auto-incremental".
It is exactly through the `WebSocket` mechanism that `GOACCESS` sends the data to the report, 
which updates the page through `JS`.

**Comment by radim-ek** [comment]
Hi @0bi-w6n-K3nobi ,
I have a CRON with `* * * * * /cron.sh` and script with `zcat -f /var/log/nginx/* | goaccess -o /var/www/info.html--log-format=COMBINED -`

So practically I have a every minute new report. And I need an refresh it manually. With `<meta http-equiv="refresh" content="XX">` I get automated new info every X minute :) 

So it's not "real-time", but it's better than nothing when I cant use WebSocket.

**Comment by allinurl** [comment]
@radim-ek can I ask, is there a reason why you can run via websockets?

**Comment by allinurl** [comment]
@radim-ek actually you can pass to goaccess the option `--html-custom-js=<file.js>`, and just add to the file:

```
window.setTimeout( function() {
  window.location.reload();
}, 60000);
```

That should help, let me know if how that goes.

**Comment by radim-ek** [comment]
> let me know if how that goes.
Love you ❤ :) Thanks!
