### ISSUE TITLE
Increase max-items for minute specificity

### ISSUE THREAD

**Issue by WBTMagnum** [allinurl/goaccess#2324]
# Problem
When using `--date-spec=min` the visitor's graph does only show the past 6 hours. This is probably fine for real-time reporting, but not suitable to generate daily graphs. Turns out, this behavior is related to `--max-items` defaulting to `366`.

# Proposal
When `--date-spec=min` is set, the default for `--max-items` could be increased to `1440` to display the data for the last 24 hours.

**Alternative:** If the described use case (daily graphs) is not strong enough, a note in the [man pages](https://goaccess.io/man#:~:text=%2D%2Ddate%2Dspec%3D%3Cdate%7Chr%7Cmin%3E) could be added, indicating, that number of displayed data point might be increased via `--max-items` to render a longer time range.

# Side note
While searching for an answer to my problem, I found two ticket that are probably fixed and could be closed:
1. [Need ability to break down VISITORS data by minute (#2277)](https://github.com/allinurl/goaccess/issues/2277#)
2. [Add option to use actual minutes, instead of every 'tenth minute' (#1251)](https://github.com/allinurl/goaccess/issues/1251#)

**Comment by allinurl** [comment]
I agree. I've made the change, it should now default to 1440 when `--date-spec=min`. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. Otherwise, it will be pushed out in the upcoming release.

Thanks for the feedback!
