### ISSUE TITLE
Report only covers the most recent year

### ISSUE THREAD

**Issue by Kodiologist** [allinurl/goaccess#2417]
In GoAccess 1.5.5, when I look at an HTML report for logs covering 28 May 2018 through 12 Nov 2022 (as seemingly verified by the text "28/MAY/2018 — 12/NOV/2022" in the upper-right), the first panel, "UNIQUE VISITORS PER DAY", only covers 12 Nov 2021 through 12 Nov 2022. It's not clear if this limitation also applies to the other panels. At any rate, I don't know if it's intentional, but it seems clearly undesirable in the general case to simply not report on some of the data.

#766 mentions this issue in passing. #117 might obviate it, but it seems like GoAccess would need the ability to report on earlier years to begin with before it can filter this data in a sophisticated way.

**Comment by allinurl** [comment]
The date range "28/MAY/2018 — 12/NOV/2022" is correct since it gathers all data within that range and computes it to get top data. However, the visitors panel (first panel) does not show top data but data points indexed in time order. 

I agree that we could make that more clear to the user. Each panel has a short description underneath the header. e.g., 'TOP OPERATING SYSTEMS SORTED BY HITS [, AVGTS, CUMTS, MAXTS]', I wonder if we need to update those labels and add a better description. Thoughts?

**Comment by Kodiologist** [comment]
Oh yeah, if I set `--max-items` to the number of days that are covered by the logs, then they'll all be included in the first panel. So the reason that only one year is included by default is that the default value of `--max-items` is 366? I had no idea. Confusingly, the documentation says "Only the CSV and JSON output allow a maximum number greater than the default value of 366 (or 50 in the real-time HTML output) items per panel."

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
