### ISSUE TITLE
showing incorrect count for just for one api 

### ISSUE THREAD

**Issue by hitesh616** [allinurl/goaccess#2532]
hi im using this goaccess tool and i observe that the for one api count of hits is missmatch. i check the in log file it showing the total count and after that if i m seeing in generated html report it showing less hit count of that api  help me with it

**Comment by allinurl** [comment]
In order to investigate the issue and understand what might be happening, it would be helpful if you could provide the complete log or a subset of it with a few lines. This will allow me to analyze and identify any discrepancies or reasons behind the problem. Please feel free to attach the log here and provide the relevant numbers you are encountering.

**Comment by hitesh616** [comment]
![Screenshot from 2023-06-28 09-37-15](https://github.com/allinurl/goaccess/assets/98729306/aef65cc9-a131-483c-b9c5-18824ca76db7)

in this picture it showing the count that api 422 which is actually correct i crossed checked  but if  i genrated the html report of that log file other apis count is getting correct but just for one api its showing inaccurate 

![Screenshot from 2023-06-28 09-58-08(1)](https://github.com/allinurl/goaccess/assets/98729306/a7aec795-2171-4be2-b192-d270c04433ba)
 
i checked the multiple time please help me with it

**Comment by hitesh616** [comment]
i got the solution thanks for the help
