### ISSUE TITLE
append data equal awstats

### ISSUE THREAD

**Issue by joubertredrat** [allinurl/goaccess#255]
Hi,
Is possible to support append data? In same moments old logs is removed, because this I need to apeend data, on awstats works fine, but I don't know if GoAccess support this.

**Comment by allinurl** [comment]
You can store parsed data using the on-disk store `--keep-db-files`. Later you can load the persisted data using `--load-from-disk`. For this you will need to use TokyoCabinet. Please take a look at this [section](http://goaccess.io/faq#tokyo-build) and [this](http://goaccess.io/man#storage).

**Comment by allinurl** [comment]
Closing this. Feel free to reopen or comment if needed.

**Comment by cttwapps** [comment]
I kinda have this question as well but I'm not sure I'm using --keep-db-files and --load-from-disk correctly.  What I'm looking for is insulation against logs that have been removed. 

If I run goaccess on a new sample log that has 5 lines with keep-db-files and load-from-disk set to true in the conf file I get a report with total requests equal to 5; this is expected.

If I pump 3 lines into the log manually my log is now 8 lines.

If I run goaccess again the report will  show total requests as 13; which appears to be the 5 lines it already processed and persisted to TokyoCabinet PLUS the lines in the log.

What I'm trying to create is a rolling report so that if a log is removed (say via log rotate) my report will still show the data from the log previously parsed.

I know I'm doing something wrong but I don't know what.  Any help/advice is greatly appreciated.

**Comment by allinurl** [comment]
@cttwapps Good question and I think this is related to issue #334. However, one way you could approach this is not to specify the log file (w/o `-f`) and just load your data with `--keep-db-files` and `--load-from-disk`. That's going to load the persisted data without altering the current stats. So for instance,

Parse last month access log

    goaccess -f access.log.1 --keep-db-files 

Then append this month access log or any new log, and preserve new data

    goaccess -f access.log --load-from-disk --keep-db-files

and then to read-only persisted data (without parsing/adding new data)

    goaccess --load-from-disk --keep-db-files

**Comment by joydashy** [comment]
I am also looking to do this, but have a problem or I don't understand fully:
> goaccess -f access.log --load-from-disk --keep-db-files

If you run this multiple times, it keeps adding duplicate records to the DB. So how to make a rolling stats file that is updated say every minute?

**Comment by joydashy** [comment]
Ah right, found https://github.com/allinurl/goaccess/issues/334 now.
