### ISSUE TITLE
deb.goaccess.io for Ubuntu 24.04 noble fails

### ISSUE THREAD

**Issue by rob4226** [allinurl/goaccess#2675]
Hi,

Just FYI the apt repo at `deb.goaccess.io` doesn't appear to have `noble` available (Ubuntu 24.04 LTS released 4/25/24). Will this be added?

Thanks!

```log
Err:7 https://deb.goaccess.io noble Release
  404  Not Found [IP: 172.110.195.161 443]
E: The repository 'https://deb.goaccess.io noble Release' does not have a Release file.
```

```sh
deb [signed-by=/etc/apt/keyrings/goaccess.gpg arch=amd64] https://deb.goaccess.io/ noble main
```

**Comment by allinurl** [comment]
I appreciate the heads-up. It completely slipped my mind. I included all the files in the repository a few weeks back but forgot to add "noble" to the config file. As a result, it seemed like it never got deployed. 

Could you please give it another shot and confirm if the issue is resolved by pulling the deb package now?

**Comment by rob4226** [comment]
@allinurl Yup it works great now! Thanks a lot!!
