### ISSUE TITLE
Incremental feature from a new log

### ISSUE THREAD

**Issue by Raboo** [allinurl/goaccess#269]
Hi,
I would like to suggest a feature..
A incremental feature.
Say you have a cron job running goaccess for yesterdays log every day.
How about combining multiple old reports into one big report without the original access log?
i.e. you output a goaccess cvs or whatever format, then ask goaccess to combine them to get like full week or month reports.

**Comment by allinurl** [comment]
Currently, using the on-disk storage, it is possible to have persisted data loaded into a report (without the original access log), however, the incremental part only works if new data is appended to the new access log. 

You can use this by configuring goaccess as `./configure --enable-tcb=btree` and then use a combination of `--keep-db-files` and `--load-from-disk`.

I can add the incremental part when loading the new log. Thanks

**Comment by Raboo** [comment]
I'm using the deb packages provided by goaccess.io. It's not built with btree..

\# goaccess -s
Built using GLib On-Memory Hash database.

**Comment by allinurl** [comment]
For data persistence, you will need to compile goaccess and use `--enable-tcb=btree`

**Comment by allinurl** [comment]
Added the ability to process logs incrementally.

That is, it will combine previously persisted data with a new data set. This is how it works:

If a data set is persisted with `--keep-db-files`, then using `--load-from-disk` will load the original data set. If new data is passed (piped or through a log file), it will append it to the original data set. 

**Note:** To preserve the data at all times, `--keep-db-files` must be used. If `--load-from-disk` is used without `--keep-db-files`, database files will be deleted upon closing the program.

e.g.,

    // last month access log
    goaccess -f access.log.1 --keep-db-files

then

    // current access log
    goaccess -f access.log --load-from-disk --keep-db-files

To read persisted data only (without parsing new data)

    goaccess --load-from-disk --keep-db-files

Feel free to build from [dev](http://goaccess.io/download#build), otherwise, it will be pushed out in the upcoming version.

**Comment by Raboo** [comment]
cool, will test this new feature.
thanks
