### ISSUE TITLE
GoAccess Time format not working

### ISSUE THREAD

**Issue by icodetlrn** [allinurl/goaccess#2765]
**cat simple.log**
05/Dec/2024:10:23:40 +0530 200

**goaccess command**
goaccess simple.log --log-format='%d/%b/%Y:%T %z %s' --date-format=%d/%b/%Y --time-format=%T

**error**
Cleaning up resources...
==541637== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==541637== https://goaccess.io - <hello@goaccess.io>
==541637== Released under the MIT License.
==541637==
==541637== FILE: simple.log
==541637== Parsed 1 lines producing the following errors:
==541637==
==541637== Token '05' doesn't match specifier '%d'
==541637==
==541637== Format Errors - Verify your log/date/time format

**Comment by heyainsleymae** [comment]
When specifying a log format, `%d` refers to a date field that matches the format specified by the `--date-format` option, rather than the `strftime` definition of "day of the month as a decimal number". You can also use `%t` to refer to the format specified by the `--time-format` option. With those changes, the updated command would then be:
```
goaccess simple.log --log-format='%d:%t %z %s' --date-format=%d/%b/%Y --time-format=%T
```

If you ran that command, you would receive the following error:
```
==98625== IPv4/6 is required.
```

This is because the IP address is a required field. Per the manual:
> GoAccess **requires** the following fields:
> - a valid IPv4/6 `%h`
> - a valid date `%d`
> - the request `%r`

You'll need to adjust your logs to include not only a position for the IP address, but also `%r`—or [the specifiers for its component parts](https://goaccess.io/man#custom-log)—in order for GoAccess to parse them successfully.
