### ISSUE TITLE
What does the bar char mean

### ISSUE THREAD

**Issue by gxhllj** [allinurl/goaccess#341]
sorry， I don't understand the data of  bar chart  in some panels .How does the data calculate out?
I noticed that in my Visitor hostnames and IPs panel ,the hits in the bar chart is even 100%.

**Comment by allinurl** [comment]
As far as the bar percentages, these are based on the maximum value of a particular metric, i.e., hits or visitors.

![2015-12-14-065641_976x55_scrot](https://cloud.githubusercontent.com/assets/5005367/11781472/c4f14f0a-a22f-11e5-89a8-d9ac60fe6a5c.png)

For instance, `04/Dec/2010` hits bar is 100% since 17,748 is the maximum hits value for the whole panel. The same for visitors, `04/Dec/2010` visitors bar is set to 100% since 1,543 is the maximum value. So for `03/Dec/2010`, 1,439 visitors out of 1,543 account 93% and 17,477 hits out of 17,748 account 98%.

BTW, this is changing on v1.0, it will more readable with a different visualization.

Hope this makes sense, otherwise let me know.

**Comment by gxhllj** [comment]
But I noticed that in my Time Distribution panel there not existed any bar be set to 100%, 
and in my  Visitor Hostnames and IPs panel   not existed any   visitor bar be set to 100%,.
According to you, there must existed one bar 100% for each vistors and hits; 
@allinurl

**Comment by allinurl** [comment]
Can you please post a link to your report or a screenshot so I can take a look at it? Also make sure to expand the panel to see all the rows.

**Comment by gxhllj** [comment]
sorry， I can't provide the link for it's the commpany's  site.
Can I email you ?
@allinurl

**Comment by gxhllj** [comment]
I find the data of this link is just like mine.
http://goaccess.io/goaccess_html_report.html?201510270000

In Time Distribution panel not existed any  bar be set to 100%
In Visitor hostnames and IPs panel not existed any visitors bar be set to 100%,.
@allinurl

**Comment by allinurl** [comment]
In the sample report posted, 12 is set to 100% for hits and 11 is set to 100% for visitors. Please make sure to click the expand icon in the upper-right corner of the table to see more data.

**Comment by gxhllj** [comment]
sorry.
I understand.
Thanks.
