### ISSUE TITLE
Suggestion: improvements for incremental analysis

### ISSUE THREAD

**Issue by e-ruiz** [allinurl/goaccess#367]
Hi!

Incremental analysis are very usefull, so, I suggest to take a look on[ PgBadger project](https://github.com/dalibo/pgbadger), what have a nice web interface to manage incremental analysis, day-by-day and week-by-week;

I hope it can be a inspiration for this project.

Some screenshots:
http://goo.gl/N0fkrg
http://goo.gl/cs86MQ

Best Regards.

**Comment by allinurl** [comment]
Thanks for the suggestion! I've been working on a major change to the web interface - it's starting to look very nice :) I hope to push this out on v1.0. There are also plans to make it real-time (still in the works). These changes should cover the default and on-disk storage.

One thing to note is that goaccess wasn't originally designed to maintain data/metrics given a time interval, will see how it develops, though.

Closing this since it will be part of issues #223, #216, #297 and probably #281.
