### ISSUE TITLE
Expected memory requirements per feature vs speed and crazy log size

### ISSUE THREAD

**Issue by LeeNX** [allinurl/goaccess#415]
More a question or outline of what features require more memory vs speed.  
  
Moving the question from #366 into an issue of it's own.  
  
I might be expecting too much of goaccess and should really be switching to some log analysing tool driven by a DB like the ELK stack, but goaccess has been making useful reports for me for so long ... Plus making me look good!!   
  
Trying to make a report for a month of traffic, I am looking at processing logs from six servers, each log for a day and compress at around 75MB per log, per day, per server ... 180 files at 9GB compressed, which hogs and kills the server at around 75% (guessing by number of requests average)

**Comment by allinurl** [comment]
I'll gather some info on this and I'll post it here. 

However, I just want to make sure that you are currently using the latest version v0.9.8. Especially since memory consumption improved by ~%44 and performance by ~37% since [**v0.9.5**](https://github.com/allinurl/goaccess/blob/master/ChangeLog#L29).

**Comment by allinurl** [comment]
Also, feel free to try the [on-disk storage](https://goaccess.io/man#storage), it will definitely consume much less memory at the price of speed.

**Comment by LeeNX** [comment]
Yip, using v0.9.8, as soon as it hit the repos ... It's was like Christmas early!! ;-)  
  
Decompressed the logs, just to see how crazy I am trying to be, we looking at 90GB of logs to process with around 239,036,280 lines, or requests for the month.  
  
Hoping to give on-disk storage a whirl when v1.0 is out, for now will just do weekly reports or limit what is useful in reports.

**Comment by allinurl** [comment]
There are several components that can help reduce memory usage. As I mentioned before, if you have a dataset that won't fit in memory, it's probably best to use the on-disk storage. The cool thing of using the on-disk storage is that you can process logs incrementally and build a report out of all of the logs, regardless their size. Again, the drawback is that data has to be committed to disk, thus making parsing slower.

The default in-memory storage has great performance since it doesn't use `(void*)` to achieve generic typing, which cause great overhead for integers. There is room for improvement on how some of the data is currently stored, so going forward, I expect memory improvements on this storage.

Here are some tips that can help reduce memory consumption:

* Depending on your log, the three request panels are probably the ones that consume the greatest amount of memory. GoAccess stores each unique request, either in memory or on disk. So if requests are **timestamped** or have **unique identifiers** within the query string, e.g., `/api?q=test&session=d41d8cd98f00b204e9800998ecf8427e&foo=bar` then it has to store all that data in order to display the relevant stats. So if you don't need the query string, you could save a lot of memory by stripping it off from the request using `-q`. Or if you want to keep it, but remove only the timestamped/uniqueid part, then you will need to do some preprocessing, e.g., 

```
cat access.log | sed 's/session=.*&//' | goaccess --log-format=COMBINED
```

* Pass `--std-geoip` to use the standard GeoIP database and avoid loading the database into memory. The drawback is that it takes a bit longer to look up each record.

* The use of `-a` increases memory usage. So if you don't need to show user-agents per host, then not using `-a` will definitely help.

* The more panels or metrics you parse/display, the more memory will use. If you don't need certain panels, avoid parsing them. You can use --[`ignore-panel=<PANEL>`](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L411) to avoid parsing and storing data for it.

Hope that helps a bit :)
