### ISSUE TITLE
Using real-time reporting features an error.

### ISSUE THREAD

**Issue by neochan78** [allinurl/goaccess#439]
hi,

1.#./configure --enable-geoip --enable-utf8 --enable-debug
2.#make  && make install
3.# goaccess -f access.log -o report.html --real-time-html
4.Unable to open fifo out: No such device or address.

how should solve?thanks!

**Comment by allinurl** [comment]
That's only a warning. It's just telling you that there's no listener for data coming in from the client so it won't pipe data out of the WebSocket server.

You can get rid of this by not passing `--enable-debug`

**Comment by neochan78** [comment]
OK,thanks
In addition, 400 error when I access the page:http:// my IP: 7890,any ideas?

**Comment by allinurl** [comment]
The port 7890 is where the WebSocket server listens. You can just open the report through port 80 or even through `file:///` such as `file:///home/user/report.html`. 

Just make sure you are pointing the report to the goaccess server using `--ws-url=SERVER_IP`, otherwise, it will attempt to connect to localhost or the same machine where your browser is running.

**Comment by neochan78** [comment]
it's working!
very thanks!

**Comment by allinurl** [comment]
Great! Feel free to reopen it if needed. Stay tuned for a minor release coming soon!

**Comment by rm3nchaca** [comment]
Thanks! I was confused with the same. Now everything is clear!

**Comment by allinurl** [comment]
Just for future reference, I added more info on **"How to generate a real-time HTML report"** to the **[FAQ](https://goaccess.io/faq)** page.
