### ISSUE TITLE
http-method and http-protocol ignored in config file

### ISSUE THREAD

**Issue by def-** [allinurl/goaccess#451]
From what I can tell `http-method false` and `http-protocol false` don't work when set in /usr/local/etc/goaccess.conf, but they work when set on the command line with `--http-method=no --http-protocol=no`. Am I doing something wrong or can someone reproduce this?

**Comment by allinurl** [comment]
Thanks for reporting this. I'm able to reproduce this. I'll have a fix for it pretty soon!

**Comment by allinurl** [comment]
Alright, I just needed to change the default value in the config file. Here's how it currently works:

Options that can be toggled, require an argument, either `<yes|no>`.
     
On the other hand, options that don't require an argument can be used simply by setting the option in the command line, i.e., `--agent-list`. Additionally, these options can have a value of 'true' in the config file which will enable the option, or 'false' and the config file parser will ignore the option.

So feel free to use yes|no in the config file, otherwise you can build from **[development](https://github.com/allinurl/goaccess#build-from-github-development)**.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed. Thanks.
