### ISSUE TITLE
Tailing multiple log files on terminal

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#459]
Our server has several vhosts.
How is it possible to use the interactive viewer with multiple files?

`goaccess -f vhost1.log -f vhost2.log # does not work currently`

Thank you.

**Comment by allinurl** [comment]
Currently it is not possible to tail multiple files. Doing a `# zcat -f access.log* | goaccess` disables the tail functionality. Please keep this open so I can take a look at it. Thanks

**Comment by Codmic** [comment]
I was also looking for this feature. When using Direct Admin, access log file names are like "domain.com.log" and the error log "domain.com.error.log". Because of this I cannot use something like "goaccess -f /var/log/nginx/domains/*.log" because it also tries to parse the error logs. Now I use the zcat option but unfortunately this breaks the very nice realtime function. It would be great if the filename could also be given using a regex.

**Comment by allinurl** [comment]
@Codmic You are right. Currently there's no way to have the real-time functionality when piping/zcat multiple log files. This will be addressed in #428.

**Comment by allinurl** [comment]
I've pushed a few commits that give the ability to output live stats from a stream or an unclosed STDIN, i.e., tail -f as well as parsing multiple logs in live mode. For example:

    goaccess --log-format=COMBINED vhost1.log vhost2.log access.log*

It also opens the possibility for live data filtering from the pipe such as:

    tail -f access.log | grep -i 'firefox' | goaccess --log-format=COMBINED -

Feel free to build from [master](https://github.com/allinurl/goaccess#build-from-github-development) to test this out, otherwise it will be pushed out in the upcoming release. Thanks.

**Comment by szepeviktor** [comment]
Very well done.

This is huge advantage in goaccess.
