### ISSUE TITLE
Log format, a headbreaker

### ISSUE THREAD

**Issue by sexybiggetje** [allinurl/goaccess#488]
Hi,

Given the following config:
`time-format %H:%M:%S %z`
`date-format %d/%b/%Y`
`log-format %h %d:%t "%r" %s %b %v "%u"`

And the following log line:

> 81.71.121.51 05/Aug/2016:15:37:28 +0200 "GET / HTTP/2.0" 200 1672 mydomain.nl "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

What is wrong with the log format? Not seeing what I've defined wrong here. Using latest stable on debian. It gives me the message "Nothing valid to process. Verify your date/time/log format."

Thanks for your effort!

**Comment by allinurl** [comment]
Great question. The parser looks for the next character after `%t`, since it's a space, then it cuts of the time before the timezone (e.g., `15:37:28`). Usually you can do this if you have a square bracket or some unique identifier, for example:

    81.71.121.51 [05/Aug/2016:15:37:28 +0200]

You could use `[%d:%t]` and have `%z` in your time-format variable.

In your case, please try this:

```
log-format %h %d:%t %^ "%r" %s %b %v "%u"
date-format %d/%b/%Y
time-format %T
```

**Comment by sexybiggetje** [comment]
That works for me, thanks. I'll change up the params as well, using brackets is a bit nicer.
