### ISSUE TITLE
Reports not displaying POST requests

### ISSUE THREAD

**Issue by clueo8** [allinurl/goaccess#507]
I'm noticing that POST requests are not showing up in either the command line console or html-report.  It just has GETS, OPTIONS, PROPFIND, but no POSTs.  Is this by design?

**Comment by allinurl** [comment]
It does displays POSTs. GoAccess displays the top 366 requests by default, so if the majority of your requests are not POSTs, then they won't show up in list.

**Comment by clueo8** [comment]
Is there any way to display REAL TIME Posts if they aren't in the top 366?

**Comment by allinurl** [comment]
You will need to do some pre-processing to your log. However, currently piping data into goaccess disables the real-time functionality (#428). Currently the workaround is to pipe the pre-processed data into a new log and feed that to goaccess.

**Comment by clueo8** [comment]
Go it, thanks!

**Comment by allinurl** [comment]
@clueo8  I've pushed a [commit](https://github.com/allinurl/goaccess/commit/c6bdee378195332f5464472fa45d7a32b9cbe1fc) that enables the ability to output live stats from a stream or an unclosed STDIN, i.e., tail -f as well as parsing multiple logs in live mode:

    goaccess --log-format=COMBINED access.log access.log.1 -o report.html --real-time-html

It also opens the possibility for live data filtering from the pipe such as:

    tail -f access.log | grep 'POST' | goaccess --log-format=COMBINED -o report.html --real-time-html -

Feel free to build from [master](https://github.com/allinurl/goaccess#build-from-github-development) to test this out, otherwise it will be pushed out in the upcoming release. Thanks.

**Comment by QGB** [comment]
tail -F access.log | docker run -p 7890:7890 -v /tmp:/tmp -i -e LANG=$LANG docker.io/allinurl/goaccess -a -o /tmp/report.html --log-format CADDY --real-time-html -

**Comment by allinurl** [comment]
@QGB Are you seeing something wrong on your end? I tried this on a quick caddy access log and got:

![2023-01-14-094424_717x110_scrot](https://user-images.githubusercontent.com/5005367/212480461-713dd62e-9543-4df2-a9f0-78cbeb9930f9.png)
