### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#512]
Test page: 
http://rt.goaccess.io/?gh

Diagnostic:
https://securityheaders.io/?q=http://rt.goaccess.io

If you enable CSP (default-src 'self'), then the test page refuses to load: 

```
[Error] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback. (wstat.html, line 1)
[Error] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback. (wstat.html, line 8)
[Error] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback. (wstat.html, line 9)
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
(wstat.html, line 1051)
```

**Comment by allinurl** [comment]
You will need to set 'unsafe-inline' and 'unsafe-eval' and set a trusted source list.

https://securityheaders.io/?q=http://rt.goaccess.io

**Comment by hdatma** [comment]
Please write the CSS in a separate file instead. 
By far, it is the best approach wrt CSS and goes along with --html-custom-css=. 

Thank you.

**Comment by allinurl** [comment]
Not sure about this. One of the original ideas behind the HTML report is the flexibility of being on a single file. For instance, you can attach the HTML file to an email and the recipient of the email will see exactly the same report. Otherwise, the user has to get into the mess of dealing with multiple files/folders and the corresponding paths.

For now I'll keep it as it is, if it becomes a bigger issue,  then I can take a look at it.

**Comment by chang-zhao** [comment]
Hello @allinurl — I would vote for separating CSS & JS.
IMHO, 'unsafe-inline' and 'unsafe-eval' ARE issue, because they are considered security risk, and I prefer to keep all the site without them.

Sending a html file by email can probably be done too, e.g. by saving from a browser as "whole page", or by leaving references to CSS & JS with absolute URl maybe.

And AFAICU eval is not really necessary...

Otherwise, maybe at least put a note in FAQ that with strict setting the page will not work, and it needs something like:

`Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"`

Anyway, thank you for a good tool. I hope it will keep improving & thriving, because it's much better to have metrics locally than to depend on external services like Google Analythics etc. Kudos! =)

**Comment by allinurl** [comment]
@chang-zhao Thanks for the feedback. For now I've added it to the [FAQ](http://goaccess.io/faq#html-report).

**Comment by gonzalo-** [comment]
Hi, there is an update on this? We cannot still using those unsafe variables to make this dashboard work... any plan to make it safer?

**Comment by allinurl** [comment]
@gonzalo- I don't see this being an issue with goaccess. Did you add the `Content-Security-Policy` to your server?

**Comment by gonzalo-** [comment]
@allinurl Sure, but those are unsafe variables, I have the security headers to make the site safe, but if I want to expose goaccess dashboard, I need to add those unsafe variables... it's not about if it works or not, it's about it should be safe.

You can see here all the recommendations: https://observatory.mozilla.org/analyze/rt.goaccess.io

**Comment by allinurl** [comment]
@gonzalo- can I ask, what errors is your browser giving you when you open the report?

**Comment by gonzalo-** [comment]
@allinurl I just saw this:

```
Last Updated: 2023-02-21 19:00:55 +0100
Dashboard
```

And the browser console:

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://foobar.com/". Either the 'unsafe-inline' keyword, a hash ('sha256-ZqhM5xQYumTdWvc5mtn7dECFuE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

foobar.html:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-rAnd0m123' https://foobar.com/". Either the 'unsafe-inline' keyword, a hash ('sha256-MRP65UuCBNbj6aQh9lLYtke1Ue4='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by allinurl** [comment]
@gonzalo- Let me think how to address this, probably as an option. One of the great advantages about goaccess is to have a self-contained single file report. Solving this would require to have those styles and JS files on different files. Which raises the question, should they live along the exported file?

**Comment by gonzalo-** [comment]
@allinurl I understand the minimalism of it and I think it's pretty cool, but if you put that against security, i will always pick to be secure, maybe add a flag for the export to separate the files?

Thanks for look at it anyway :)

**Comment by allinurl** [comment]
Great news! The feature you requested has been added. If you'd like to start using it now, you can build from [development](https://github.com/allinurl/goaccess#build-from-github-development). Alternatively, you can wait for the next release which will include this feature.

To generate an HTML report with external assets, you can use the command `goaccess -o report.html --external-assets`. This will create two separate files, `goaccess.js` and `goaccess.css`, in the same directory as your `report.html` file.

**Comment by gonzalo-** [comment]
@allinurl cool! Looks, good, I will try it as soon as I can.

Thanks!
