### ISSUE TITLE
Centralizing Apache Logs and GoAccess

### ISSUE THREAD

**Issue by fmotnaldo** [allinurl/goaccess#532]
Hi,

I recentrly discover goaccess and I got a conern regarding the logs. Thre is a way to create a centralized server to get all of the data for my seven web servers?. Someone know a way or jsut a link to check the way to do it. 

Thanks

**Comment by allinurl** [comment]
You can set your seven web servers to log traffic to a remote server. [**This**](http://rafaelsteil.com/apache-remote-logging-with-rsyslog/) is probably a bit old, but it might be helpful to get started.

**Comment by fmotnaldo** [comment]
great so I can send via rsyslog the logs there I want to be parshed in to accelog. Threfore Iw ill have the seven logs in one server. How can I integrate it in one web interface insted of each one indiviadually. There is a way or not?.

**Comment by allinurl** [comment]
All entries coming from your seven web servers will be put under the file you specified in:

    $template apacheAccess,"/var/log/apache2/access.log"

Then you can have goaccess parse that specific log on the remote server.

**Comment by fmotnaldo** [comment]
I will try that way. If I create a crontab entry that handle the logs for
that file. When I create the report it will parsed the data for each
server?.

**Comment by allinurl** [comment]
@fmotnaldo that's correct.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by codeagencybe** [comment]
Hello,

I just started digging into GoAccess and I'm looking for a solution to have a "statistics" dashboard for each of my clients their website, but I want to host it on a central server and domain like "stats.mydomain.com"

Does GoAccess support client logins etc...? I can't find anything in the docs that says so, so I'm guessing probably not....

Anybody who can share his ideas, concept how to do something like this? 
I've read in this topic about rsyslog. 
Is it better to use a custom domain per client? like stats.myclient1.com, status.myclient2.com, ....
But how to manage that client 1 can see his stats and client 2 can see his own stats, ....? 

I like GoAccess because of the nice modern interface and flexibility, I'm just not seeing how to turn this into the idea I have in my mind. 

Thanks for any feedback, much appreciated!

**Comment by allinurl** [comment]
@codeagencybe #117 will implement filters so that should simplify the filtering part. Right now you could either filter on demand by virtualhost e.g.,

    # tail -f -n +0 access.log | grep --line-buffered 'client1.com' | goaccess -o client1.html --real-time-html

or you could centralize those logs and have a bucket for each client's access log and parse them with goaccess as individual logs.
