### ISSUE TITLE
Enhancement: Live Mode

### ISSUE THREAD

**Issue by staelche** [allinurl/goaccess#582]
First of all goaccess is a really nice tool. Thanks for that!

A feature which is currently missing and would be helpful for me is a live mode. Means an option which lets goaccess just read the new log entries and build upon this data all the metrics. 

This is would be great e.g. for troubleshooting current peaks to check the requested resources and the ip(s) causing the traffic.

**Comment by allinurl** [comment]
Thanks for the suggestion. Are you looking to filter the logs you already parsed? or simply display stats as they're appended to the access log, as in the [**live demo**](http://rt.goaccess.io/?gh)?

**Comment by staelche** [comment]
Filtering is another nice feature but I saw it was already requested by different people.

I am just looking for simply displaying the stats as they are appended to the log file to get the stats based on the time goaccess is running on the command line (I am using goaccess only from the command line). Goaccess should just skip parsing the old, already existing content of the log.

This is e.g. the default behavior of ngxtop.

**Comment by allinurl** [comment]
Got it, I think this is part of issue #428.

**Comment by allinurl** [comment]
I've pushed a [commit](https://github.com/allinurl/goaccess/commit/c6bdee378195332f5464472fa45d7a32b9cbe1fc) that enables the ability to output live stats from a stream or an unclosed STDIN, i.e., tail -f. This allows to do:

    tail -f access.log | goaccess --log-format=COMBINED -

or even

    tail -f access.log | goaccess --log-format=COMBINED -o report.html --real-time-html -

It also opens the possibility for live data filtering from the pipe such as:

    tail -f access.log | grep -i 'firefox' | goaccess --log-format=COMBINED -

One thing to note is that  tail -f will keep the pipe opened even when goaccess already has exited. For instance, `tail -f syslog | grep -q 'cron'` tail will exit on SIGPIPE, however it will only get `SIGPIPE` until an extra byte is written to the tail'd file. `SIGTERM, SIGINT` should close tail fine though.

Feel free to build from [master](https://github.com/allinurl/goaccess#build-from-github-development) to test this out, otherwise it will be pushed out in the upcoming release. Thanks.
