### ISSUE TITLE
scientific notation was found in HTML

### ISSUE THREAD

**Issue by DennyDai** [allinurl/goaccess#610]
`Max: 1.01e+3 KiB`

![Screenshot 2017-01-05 at 8.01.29 AM.png](https://ooo.0o0.ooo/2017/01/05/586d8d4486afb.png)
![Screenshot 2017-01-05 at 8.01.24 AM.png](https://ooo.0o0.ooo/2017/01/05/586d8d4531dd3.png)

**Comment by allinurl** [comment]
Thanks for reporting this. I have pushed a [**commit**](https://github.com/allinurl/goaccess/commit/aab0fafe8c41a3579b82bb99754537c9f853bf71) to fix this.

Please feel free to build from [**development**](https://goaccess.io/download#build) to test this out, otherwise it will be pushed out in the upcoming release.
