### ISSUE TITLE
Data from other real time html report showing up

### ISSUE THREAD

**Issue by mmleclerc** [allinurl/goaccess#617]
I setup two real-time html reports on the same server. They each read their own different access.log files and output a differently named html file. I'm serving these files via NGINX. For some reason when I start one of the real time reports (let's call it production) and refresh the other one (let's call it sandbox,which was already running), sandbox will show the metrics of production. Whichever was started second seems to be the one showing on both reports. I've tried launching both commands while the browser was closed the opening, keeping the tabs open before launching and it made no difference.

Once the data refreshes via web socket, everything is ok. Only when I do a manual refresh do I have the problem. I've looked in the script tag with the JSON data in the sandbox report and the values are right and not what is being displayed. 

![sandbox_metrics](https://cloud.githubusercontent.com/assets/25048187/21835526/ade7a718-d78b-11e6-91c7-623c46713f8d.png)

Here are the two commands used to launch the report

`goaccess -f /vweb/tomcat8-sandbox/logs/access.log -o /www/goaccess/sandbox.html --real-time-html --html-report-title="Sandbox" --ws-url=192.168.0.1`

`goaccess -f /vweb/tomcat8-prod/logs/access.log -o /www/goaccess/production.html --real-time-html --html-report-title="Production" --ws-url=192.168.0.1 --port=7891`

This seemed to have started happening after I've modified the conf file for default settings to ignore some panels. Most likely unrelated, but who knows.

I'm using version 1.1 of goaccess on CentOS 6.8 and looking at the reports on Chrome 55.0.2883.87 m. I get the same bug on IE11 though.

This is a minor inconvenience, since if I let it update automatically I get the right data.

Let me know if you need anymore data!

**Comment by allinurl** [comment]
Thanks for reporting this. I was able to reproduce this. I'll look into it and post back as soon as I figure what's going on.

**Comment by allinurl** [comment]
I was looking at this and just noticed that you must be running GoAccess on the same pipe and thus when the second report is opened data from the first pipe (FIFO) is being sent to the second report.

To fix this you will need to assign a different fifo to each instance you are running. e.g.,
 `--fifo-in=/path/fifoin.1` and `--fifo-out=/path/fifoout.1`. 

However, issue **#575** reported that these options were not taking the new params. It has been fixed. But as of right now you will need to build from development in order for these options to work. Otherwise, it will be pushed in the upcoming version.

For example:

    goaccess -f /vweb/tomcat8-sandbox/logs/access.log -o /www/goaccess/sandbox.html --real-time-html --html-report-title="Sandbox" --ws-url=192.168.0.1 --fifo-in=/tmp/sandbox.in --fifo-out=/tmp/sandbox.out

AND

    goaccess -f /vweb/tomcat8-prod/logs/access.log -o /www/goaccess/production.html --real-time-html --html-report-title="Production" --ws-url=192.168.0.1 --port=7891 --fifo-in=/tmp/prod.in --fifo-out=/tmp/prod.out
