### ISSUE TITLE
Realtime reporting failing for me :(

### ISSUE THREAD

**Issue by Verticalmag** [allinurl/goaccess#659]
I can get static reports to work without an issue.  

When I create a report using:
 goaccess -f /var/www/vhosts/system/logs/access_log -o /var/www/vhosts/my.domain.com/log/report.html --real-time-html --ws-url=localhost

1.  I do get a static report
2. ssh just hangs in the parsing  [24,556] [24,556/s]

I read that ssl might be the issue (http://stackoverflow.com/questions/38710438/goaccess-set-the-websocket-server-to-listen-on-port-7890-and-localhost) 

So created a new subdomain with no security and same thing.  SSH hangs and I get a static report but no realtime.  

The programme is AMAZING best log viewer.  But just wish I could get past this last bug in my install.

Now I can get real-time reporting if I don't use the html display but in ssh.  It works just not as pretty or nice to work with.  

Any feed back would be helpful.  Thanks.

**Comment by allinurl** [comment]
Since you are ssh'ing into a remote machine where goaccess is running, then I'd ask you to try changing --ws-url to point to that remote machine as well as make sure port 7890 is opened. For instance,
   
    goaccess -f /var/www/vhosts/system/logs/access_log -o /var/www/vhosts/my.domain.com/log/report.html --real-time-html --ws-url=remote.machine.host.or.ip

If that doesn't solve the issue, please take a look at your browser's console, it will display the reason why is not connecting to the WebSocket server.

TLS/SSL & WSS are now supported (from v1.1) so the report should run fine under an https URL. However, you will need to build `--with-openssl` and pass `--ssl-cert=<path/cert.crt>` and `--ssl-key=<path/priv.key>` to get TLS working.

The 'hanging' part is because I haven't daemonized the process, #520 will address this. For now you can just ignore it or use `--no-progress` and append `&` to the command line.

**Comment by Verticalmag** [comment]
If the realtime is really working will I have a "GoAccess Real-Time HTML Report" title like on the example http://rt.goaccess.io/ ?

**Comment by allinurl** [comment]
If it's connected to the websocket server, then the little circle on the left-hand side bar turns green, otherwise it will be grayed out. 

To have a custom title, you can use `--html-report-title='My Title'`

**Comment by allinurl** [comment]
Were you able to figure it out? Otherwise, can you please post the content of your browser console (Ctrl+Shift+j in Chrome)? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
