### ISSUE TITLE
Unique visitors count different than Google Analytics

### ISSUE THREAD

**Issue by pako69** [allinurl/goaccess#789]
Hi
(Please my bad English, I'm French and I'm not a *nix guru :-)

I just installed latest GoAccess 1.2, I run it with:
`goaccess mydomain.com-ssl_log-Mar-2017 --time-format COMBINED --date-format COMBINED --log-format COMBINED --ignore-crawlers -o report.html`

And for just 1 month I get 44 213 unique visitors?! I would like to but it's not the reality...
Google Analytics give me only 5 055 unique visitors.

Maybe there is an option I missed?

Thanks

**Comment by allinurl** [comment]
Great question and somehow difficult to answer, however, there are for sure a couple of things to consider.

1. By default, GoAccess counts crawlers/bots as legitimate visitors. You can stop counting them using `--ignore-crawlers`. However, since it's not possible to account for all bots out there, even after you disable the most popular ones, you may still get a few in your logs.

2. Google Analytics keeps track of visitors using cookies, so if a browser has cookies or JavaScript disabled, then it won't keep track of it. This includes the now so popular adblockers and bots as well. GoAccess should be able to track these down fine since it works at the server level.

3. You can narrow down the unique visitors count to unique IPs. It will show you the total number in the upper-right corner of the panel.

4. You may be able to identify some bots/crawlers by listing the user agents of the given host. Passing `-a` will give you that list upon expanding a host in the hosts panel. Also, resolving the request IP with `-d` may give you a hint (assuming you are outputting HTML). It will add an extra column under the hosts panel (**Note**: `-d` will need to resolve all IPs and therefore the time it takes to parse will be longer)

I believe tracking visitors at the client level deflates the actual number of visitors (due to reason listed on #2). On the other hand, server-side tracking gives you a more accurate number at the cost of not knowing for sure if the client is a human behind a browser.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
