### ISSUE TITLE
Unique visitors count much greater than Google Analytics

### ISSUE THREAD

**Issue by froger-me** [allinurl/goaccess#803]
Hello,

I am confused with the results given by goaccess versus other analytics tools. As much as I understand that client-side analytics tools are somewhat unreliable, the difference in terms of result my website experiences seems unbelievably huge.

Example:
Piwik, today (last 16 hours): 12,427 visits
Go access last 16 hours (result of `sed -n '/'$(date '+%d\/%b\/%Y' -d '16 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log | goaccess -o /home/user/public_html/goaccess/monitor.html --real-time-html --ignore-crawlers`): 51,567 unique visitors

By comparison, Piwik and google analytics are very close. My user base does not typically use adblock or other script blockers.

Could you help me figure out what could be happening here?

**Comment by allinurl** [comment]
Great question and somehow difficult to answer without having access to the logs. 

However, recently a similar question was asked (**#789**), and as I mentioned over there, Google Analytics counts unique visitors differently from goaccess and my assumption must be the same for Piwik. 

Since both of them use cookies to track a visitor, then it's possible that the same user could visit your website using different IPs while the cookie still living in their browser (same laptop, different locations) — That could be one of the things you are experiencing. 

On the other hand, GoAccess considers requests containing the same IP, same date (e.g., `12/Jun/2017`), and the same user agent a unique visitor. This is due to the nature of GoAccess attempting to get an accurate picture of what's happening at the server level as opposed to a marketing level of your website.

I'd suggest taking a small data set from your access log, e.g., 50-100 lines and then parsing it with goaccess. Take a look at the unique visitors count and see if it matches what you expect by looking at the log entries manually.

Now if you can run the same data set in any of the other tools (probably not possible with Google Analytics), then you may get an idea on how the numbers differ.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
