### ISSUE TITLE
Insecure temporary file names

### ISSUE THREAD

**Issue by geraldcombs** [allinurl/goaccess#805]
When built with --enable-tcb=btree, GoAccess appears to use predictable filenames under /tmp by default. This is a security vulnerability as described at https://www.owasp.org/index.php/Insecure_Temporary_File. For example, if an attacker creates the symlink /tmp/1mdb_datamap.tcb which points to /etc/shadow and I subsequently run GoAccess, hilarity will ensue.

**Comment by allinurl** [comment]
Thanks for reporting this. I'll look into it and push a fix as soon as possible.

**Comment by allinurl** [comment]
I've pushed a [commit](https://github.com/allinurl/goaccess/commit/218424d390d8eef1519cd36ef59647dfcbcf6cba) that should fix this issue.  Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) otherwise it will be pushed out in the upcoming version.

Thanks again for the heads up on this.
