### ISSUE TITLE
Docker release does not honor max-items parameter

### ISSUE THREAD

**Issue by klemenkobetic** [allinurl/goaccess#810]
I'm using goaccess in a docker container and it seems I have some problems using max-items (I would like to set it to more). Should this work?

```
# Write  output to stdout given one of the following files and the
# corresponding extension for the output format:
#
# /path/file.csv  - Comma-separated values (CSV)
# /path/file.json - JSON (JavaScript Object Notation)
# /path/file.html - HTML
#
output-format /srv/report/file.csv

--> So the output is csv.

# Maximum number of items to show per panel.
# Note: Only the CSV and JSON outputs allow a maximum greater than the
# default value of 366.
#
max-items 300
#max-items 700
```

If I set it to 300, it works, it limits the results to 300
If I set it to 700, it limits the results to 365

According to the documentation :

    --max-items=<num>

    The maximum number of items to display per panel. The maximum can be a number between 1 and n.
    Note: Only the CSV and JSON output allow a maximum number greater than the default value of 366 (or 50 in the real-time HTML output) items per panel.

What am I miss-using and does n have a maximum?

**Comment by allinurl** [comment]
This issue should be fixed per this [commit](https://github.com/allinurl/goaccess/commit/2fb119c95545ad8662deafaacdbd804be4e18a87).

Please feel free to try it out. There's a new way of building from Docker which uses the github repo instead of an apk from Alpine. Please take a look at the instructions [**here**](https://github.com/allinurl/goaccess#docker).
