### ISSUE TITLE
How to build goaccess with GeoIP support

### ISSUE THREAD

**Issue by miloden81** [allinurl/goaccess#829]
Dude, you have a very bad faq on website...

I made the following and can't find GeoIP in report section...

```
sudo apt-get install libncursesw5-dev libgeoip-dev
wget http://tar.goaccess.io/goaccess-1.0.2.tar.gz
tar -xzvf goaccess-1.0.2.tar.gz
cd goaccess-1.0.2/
sudo ./configure --enable-geoip=mmdb --enable-utf8
sudo make
sudo make install 
```

also can you explain step by step shy do i need for real-time report?
thanks

**Comment by allinurl** [comment]
The [**download**](https://goaccess.io/download#installation) and [**man page**](https://goaccess.io/man#configuration) list the GeoIP config options, so since you are using `mmdb`, it requires  GeoIP2 databases which you need to [**install**](https://github.com/maxmind/libmaxminddb#installation) from source as it is not on the debian/ubuntu repo. However, if you want to make things easier, just configure goaccess using `--enable-geoip=legacy` and it should work out of the box.

For a real time HTML report, all you need is to run goaccess with `--real-time-html` and save your output report to your web server's public www folder, e.g., `/var/www/mysite.com/report.html`. Then you should be able  to point your browser to `mysite.com/report.html`. For instance,

    goaccess access.log -o /var/www/mysite.com/report.html --real-time-html

**Comment by miloden81** [comment]
Thanks for fast answer.

--enable-geoip=legacy 
i got an error message:

goaccess: unrecognized option '--geoip-database'

**Comment by allinurl** [comment]
Please download the [**latest version**](https://goaccess.io/download) of goaccess.

**Comment by miloden81** [comment]
Do i need make uninstall prior to installing the new version?

**Comment by allinurl** [comment]
Yes, you do:

```
$ curl tar.goaccess.io/goaccess-1.2.tar.gz | tar xvz
$ cd goaccess-1.2/
$ sudo make uninstall
$ ./configure --enable-geoip=legacy --enable-utf8
$ make
$ sudo make install
```
