### ISSUE TITLE
Next release of GoAccess

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#851]
There are a number of commits since last release

https://github.com/allinurl/goaccess/compare/85cdf89f8f26b584168cf3a9a9941f80d769e2ee...master

Do you plan to release 1.3?

**Comment by allinurl** [comment]
I certainly plan to release 1.3, however, there are still a few milestones I want to reach, such as #334, #832, and hopefully I can nail down #708/#813 (which are haunting me). Closing those will make it a nice release :)

**Comment by szepeviktor** [comment]
Seem like the community is not that active, all 4 PRs are open.

**Comment by allinurl** [comment]
A different project is taking a lot of my time, I certainly need to start pushing out some major commits though. #708/#813 needs to be addressed in my opinion before the next release is pushed out. Otherwise, it may be worth replacing tokyocabinet with something more stable or roll-out our own. I just closed 2 PRs, only your is left, which I need to look in the next deb packaging.

**Comment by szepeviktor** [comment]
@allinurl Do you plan to release a new version this year?

**Comment by allinurl** [comment]
There are a couple of PRs opened at this time. However, by no means this is an indication of the project not being active. There is a chance that the current on-disk storage will go away, so before merging them, I need to check if the new on-disk storage will be pushed out.  Probably there won't be a release this year, I believe at this point it's better to push a  a major release.

**Comment by szepeviktor** [comment]
@allinurl I think it may take some time to resolve bugs
https://github.com/allinurl/goaccess/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by allinurl** [comment]
@szepeviktor Indeed it will take some time, however, several of them are dups and should be taken care of once the on-disk btree is replaced. If possible, feel free to check any of them.

**Comment by szepeviktor** [comment]
@allinurl What kind of help would advance the next release?

**Comment by allinurl** [comment]
I'm halfway implementing the new on-disk storage in an attempt to fix [these](https://github.com/allinurl/goaccess/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aon-disk+label%3Abug) issues.  Once I get this done and have it fully tested I plan to push this release for sure. In between, I may be able to address a few other opened issues. I'm certainly aware of how behind this release is :( 

Please feel free to take any issues you feel comfortable with, it's always very helpful and appreciated.

**Comment by szepeviktor** [comment]
It seems like on-disk storage needs a lot of changes in the code.

**Comment by szepeviktor** [comment]
Hello @allinurl !

Do you have plans to fix the on-disk bug/s and make a release?

**Comment by allinurl** [comment]
Hello @szepeviktor, yes I certainly have plans to finish fixing that issue and to push the next release. Last few months have been crazy busy here, should be better in the upcoming weeks though.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Hello @allinurl !

Do you plan to fix the on-disk storage issue and make a release?

**Comment by allinurl** [comment]
@szepeviktor Yes I do. Working on it as of this post :)

**Comment by justinmayer** [comment]
Looking forward to the next release. If I may humbly make a few suggestions...

* When the next version (1.3) is released, immediately create a new issue to track the next version (say, 1.4). That allows folks to subscribe to the "Release next version" issue and thus know once it's been released. (I use this technique for [Pelican](https://github.com/getpelican/pelican), and folks seem to find it very useful.)

* [Create milestones](https://github.com/allinurl/goaccess/milestones) for the 1.3 release and also the next 1.4 release, adding the most important issues as appropriate, including the [aforementioned](https://github.com/allinurl/goaccess/issues/851#issuecomment-318141096) ones. That makes it easier to understand what's holding up the release, and can help determine which issues are truly critical and which can/should be deferred to a subsequent release in order to maintain a more frequent release cadence.

* Release new versions more frequently, even if they aren't "complete" or "ready". This project has about new 550 commits since 1.2 was released, none of which are being used by the vast majority of users because they aren't in a shipping release. This is a very difficult discipline to develop and put into practice, and I am _terrible_ at it. Look no further than Pelican, which hasn't seen a release in a similar timeframe! But I am making a commitment to releasing more frequently, and I think GoAccess would benefit from a similar practice.

For what it's worth, I am more than willing to assist with any of the above issue/milestone management tasks if that is helpful. Just say the word, and I'll get to work on it!  😁

**Comment by allinurl** [comment]
v1.3 was pushed out last Friday Nov 23th. Closing this. Thanks!

**Comment by szepeviktor** [comment]
Thank you!


:) I wait for 1.3.1 with all the bugs fixed.

**Comment by justinmayer** [comment]
Awesome! Are there any upgrade notes for those upgrading from v1.2 via Debian packaging? Any configuration file changes required? Or is it as simple as `apt upgrade goaccess`?

**Comment by allinurl** [comment]
@justinmayer Great question. `apt upgrade goaccess` should do the job. 

Only minor installation change is where the conf file is placed, before it was under `/etc/goaccess.conf` now is under `/etc/goaccess/goaccess.conf`. Also, you may want to expand your [browsers.list](https://raw.githubusercontent.com/allinurl/goaccess/master/config/browsers.list) as needed and use `-b /path/browsers.list`.
