### ISSUE TITLE
Date and Time filter in GoAccess

### ISSUE THREAD

**Issue by BipinBahuguna** [allinurl/goaccess#882]
Hi,

I have configured go access dashboard with HTML page.

/usr/local/bin/goaccess -a -f /tmp/dis2.log -o /var/www/html/example.com.html

Is there any way to filter date and time in that dashboard ???

Thanks,
Bipin Bahuguna

**Comment by allinurl** [comment]
**#117** will add filters within the dashboard. Right now you can use a data filter such as grep, awk, sed, etc to filter your data set and feed that to goaccess in real-time. e.g., 

    # sed -n '/'$(date '+%d\/%b\/%Y' -d '1 week ago')'/,$ p' /tmp/dis2.log | goaccess -a - -o /var/www/html/example.com.html

Take a look at the [**examples**](https://goaccess.io/man#examples) page for some neat pipes. Otherwise feel free to post exactly what you are looking to filter and I can take a look.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by pfergi42** [comment]
Would still be nice to have date filters in the HTML output. ;)

**Comment by allinurl** [comment]
@pfergi42 **#117** would address this.

**Comment by edjekadetje** [comment]
Any idea if this will still happen, its a bit useless when it starts fresh every month, it should show the last 30-60 days, instead of start fresh each month.

**Comment by allinurl** [comment]
@edjekadetje [stay tuned](https://x.com/goaccess?lang=en), working on it as we speak.
