### ISSUE TITLE
SSL certificate for deb.goaccess.io is invalid when adding apt repository

### ISSUE THREAD

**Issue by amartin3225** [allinurl/goaccess#883]
I am attempting to install GoAccess on Ubuntu 16.04 using the GoAccess apt repository following the steps here:
https://goaccess.io/download

When I attempt to add the key (https://deb.goaccess.io/gnugpg.key), I receive the following error:
```
hostname 'deb.goaccess.io' doesn't match 'goaccess.io'
```

I can also reproduce this error if I try to view the key in Google Chrome (the page is reported as insecure). Could you please update the SSL certificate for deb.goaccess.io or move the `gnugpg.key` file to goaccess.io rather than deb.goaccess.io?

**Comment by allinurl** [comment]
Interesting. I spun up a virtual machine with vanilla Ubuntu 16.04 x64 and I don't get this message, neither from Chrome (61.0.3163) nor wget. SNIs should be supported on both of them. Are you able to test this on a different machine?

**Comment by asmartin** [comment]
I was mistaken - this is actually an Ubuntu 14.04 machine; the version of Python on 14.04 is old enough that it does not support SNI (requires >= 2.7.9). I tried to get SNI support working by installing the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules but could not get it to work. I confirmed via [this SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=deb.goaccess.io&hideResults=on) that the problem is SNI: without it, the certificate is not considered valid. For now I've just cached the file locally for when I need to install GoAccess on Ubuntu 14.04. Feel free to close out this ticket if you feel this is an acceptable solution for Ubuntu 14.04.

**Comment by allinurl** [comment]
Thanks for the heads-up. Just made some updates to the list of ciphers for this server. Moving the key to goaccess.io would present the same issue since Python would still need SNI support.  

`wget` should support SNI since it was added in version 1.14 (trusty ships 1.15).
