### ISSUE TITLE
Relational diagrams for tcb storage

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#886]
GoAccess - 1.2.
Using: [Official GoAccess' Debian/Ubuntu Repository](https://goaccess.io/download#official-repo) on xenial

@allinurl do you have any tcb relational storage diagrams that can be posted up, so I can see how they interrelate to one another?  In particular, how to identify all records associated with a particular date.  A graphviz dot file would be awesome but I'll take anything even if scribbled on the back of a napkin with magic ink.  :)

The project is trying to figure out how to prune out any entries that are older than 31 days.  The end goal is to inject a new log file at end of day and remove anything older than the set window.

The main reason is I'm working with some pretty big log files that are getting drug down to around ~200/s to ~900/s, with my peak speeds being around 5.7K/s.  I have all panels enabled FWIW.  One set of log files I'm working with, it cranks for a few days worth, then bogs down into heavy disk I/O which is most likely from heavy hash collisions on the referrers.  Even with the stock config, it will still bog down.
https://github.com/TerraTech/goaccess/wiki/Performance

In conclusion:
1) keep a current 31 day rolling window (non-compressed)
2) ability to extract >31 days to a separate directory and store(/merge) in tcb files for archival, most likely will store current year (stored on a btrfs compressed filesystem)

Overall, I really like how goaccess represents the log file data visually, but I'm running into a brick wall on how to implement this with nightly processing on a massive scale that runs in a reasonable time for a large number of domains.  For those with small log files, it runs great (~3K/s - 6K/s) - but the larger log files, the processing time hits a major brick wall (<900/s) as the data accumulates and periodically stalls during processing by heavy disk I/O.  My nightly stats processing window, is roughly two hours and handles several gigabytes of gzip'd (-9) logs per server.

**Comment by TerraTech** [comment]
Thinking about it, since it doesn't really start to bog down until after 4 or 5 days are run on the 'xav' set, is there a way to just process that one day, and then merge it into the bigger set in a more efficient manner that would minimize lookups as much as possible and avoid the tarpitting?  I'm thinking no, because that should be in effect what goaccess is already doing.

**Comment by allinurl** [comment]
Great question! Regarding the first part, I don't have a diagram for the tcb storage. The closest to understand how the tables are interrelated would be the brief description in the comments found on the [**header file**](https://github.com/allinurl/goaccess/blob/master/src/tcabdb.h#L45). I probably can create one and post it here as soon as I get a chance (working on the upcoming version).

However, to make it a bit more challenging, GoAccess does not store a timestamp for each record, but instead, it simply stores a key-value pair depending on the type of record. It does this so it can easily get the top values for each panel. This certainly makes it more difficult to get rid of old data. 

Actually I've been looking at different DBs out there that may perform better or perhaps implementing something that fits exactly the needs of goaccess, still need to look further into this, though. 

From what I understand is that you would like to archive a report containing 31 days of data? if that's the case and assuming it fits in memory, then you could try using the default hash tables instead of tcb (on a 8GB ram machine, I was able to fit a 100M hits, however this can vary depending on the data), this will certainly give you a much better performance. Now, to store the whole year, then it's likely you would need tcb, which I'm thinking you could do it incrementally (e.g., parse 1 week worth of logs). Are you currently using `--load-from-disk` & `--keep-db-files`?

**Comment by TerraTech** [comment]
Closing this as the data store really isn't relational, and the header files provide the documentation required to figure out the TCB/file structure.
