### ISSUE TITLE
Current performance and incremental reports

### ISSUE THREAD

**Issue by AnomalRoil** [allinurl/goaccess#935]
Hello,

I've been trying out goaccess to process a lots of logs lately (I've got 2.5M hits a day to log just on my Nginx, I didn't dare parse the Varnish logs yet) and I really like the HTML report since it allows me to share data easily with admins of the website not involved with the sysadmin stuff.

Now, one thing I tried to do is complete dashboard of our logs over the last 6 months for example, but then it would mean I should be feeding way too much data into goaccess: one week worth of log is a 6.8G file with 23M lines, which means that 6 months are really a ton of data.
So I tried to go around this in an incremental way, parsing stuff slowly... (in order to get some reports)

Now, I've got two problems, my first problem is regarding the current performance. You say in your FAQ that on a  i7-4510U CPU @ 2.00GHz 8GB RAM, you get: 

Benchmark full features & metrics enabled (>=v0.9.5) - Default Hash Tables | 87,816 lines per second
-- | --
Benchmark full features & metrics enabled (>=v0.9.5) - On-Disk B+ Tree | 23,000 lines per second
Benchmark full features & metrics enabled (>=v0.9.5) - In-memory hash table | 46,000 lines per second

Plus you mention that 
> A dataset of about 52M hits (12GB size) is parsed in 20 mins (in-memory), 60 mins (on-disk storage). 

On my side, when parsing my latest access log using for example:
```
goaccess -o /srv/www/stats/last.html --log-format=COMBINED -f /var/log/nginx/access.log.1
```               
I obtain **way slower** parsing speed, with the parsing indicating `[2900/s]`.
Is this normal? Are there specific configurations to parse faster? 
(I believe I've got a decent server:  Intel C2750, 8 core @ 2.40 GHz , 16GB and 250 GB SSD, so I would expect parsing as fast as the FAQ mentioned.)
The parsing of this file took me many hours. (I didn't count, but it's over 4h).

So the performance seems to be almost 2 orders of magnitude below what you obtained. 
This is my first question: am I at fault, or is this a know regression since you published the FAQ ?

Now, I've also tried out using the `--keep-db-files --load-from-disk` commands, but since I don't really care about building a db, I don't see any benefits for me to do it so, excepted that it's the only way to go around it if I'm not willing to feed all logs at once in goaccess.  

Note that I've compiled the latest release using: 
```
./configure --enable-utf8 --enable-geoip=legacy --with-openssl --enable-tcb=btree
```

So I wonder if you have a way to add information to the report incrementally?  I mean running for example something like:
```
goaccess -o /srv/www/stats/last.html --log-format=COMBINED -f /var/log/nginx/access.log.1
goaccess --incremental-add -o /srv/www/stats/last.html --log-format=COMBINED -f /var/log/nginx/access.log.2
```
but without overwriting the report, simply appending the new data to the existing report, without any need to store all the previous data in a database or to run on all files at once.
Or if this is a feature that could possibly be added?

PS: maybe I am simply not using the tool as intended, and I should be changing my workflow. How are you going around having tons of logs to get reports over multiple months?

**Comment by allinurl** [comment]
Great question and thanks for pointing this out! 

I have revised the benchmarks and you are correct, the numbers are certainly different than in v0.9.5 as new features have been introduced since then. I have updated the numbers to reflect the parsing time on the same machine. Please take a look at the [**FAQ**](https://goaccess.io/faq) for the updated version.

As far as `--keep-db-files --load-from-disk`, as you said, if you are not really building a db, then there's no need for those two options, I'd simply run goaccess without them. However, you bring a good point of having the ability to simply adding up the numbers to an existing HTML report. 

So to answer your question, no, it's not currently possible, but I definitely see the advantage of it. I plan to address this in **#631**. Though, the only downside is that it wouldn't work on the terminal output and neither in the CSV output (may be hard to implement). I don't think it would be too difficult to implement this as currently the HTML reports simply spits out a JSON object, thus adding up the numbers to the existing JSON object shouldn't (in theory) be too hard.

My suggestion for your case  is:

Give the default hash tables a shot and see how much memory a week worth of logs is consuming and try to tune some of your options to parse larger logs. Take a look at [**this post**](https://github.com/allinurl/goaccess/issues/572#issuecomment-260968331) for some details on it. However, if there's no way to fit the whole dataset in memory, then try the on-disk db.

As a side note, Tokyo Cabinet is going away as the performance hasn't been great and it's susceptible to DB corruption which some users have reported already. I'm working on an implementation of LMDB, hoping to test it soon and see how it performs.

**Comment by AnomalRoil** [comment]
Thanks for the quick feedback!

Regarding the updated FAQ, I'm finding it strange to see such a huge difference between my benchmarks and yours. What command line are you running?

I've tried using:
```
goaccess -o /srv/www/stats/0.html --log-format=COMBINED -f /var/log/nginx/access.log -q
```
and it's going at: [4600/s], with a CPU usage of 100% on one core and a memory usage of 200M so far.

I guess I've got some bottleneck somewhere, excepted if your i7 processor is actually leveraging Intel Turbo boost and thus is clocked way higher than its nominal clock when processing the logs.
Does the speed primarily depend on the CPU clock, from your tests?

I've seen on #334 that I'm not alone trying to get lengthy report. And thanks for #631, I missed it.

PS: or maybe I should be recompiling goaccess to use the default hash tables? (I mean, I thought the TC were used only if `--keep-db-files --load-from-disk` is set...)

**Comment by TerraTech** [comment]
@allinurl In regards to LMDB, we still have a lot of servers on 32bit OSes, mostly due to memory constraints and/or avoiding 64bit pointer/etc overhead.  Since LMDB + 32bit can't write out >4GB, I'd like to see the option to retain/select Tokyo Cabinet (TC) at compile time (since it can).  IOW, don't throw out TC but rather have the ability to select which hash backing store you want to use.  Also, adding a utility that can migrate existing TC files ==> LMDB would be nice -or- just allow goaccess the ability to read from both for backwards compatibility.

**Comment by allinurl** [comment]
@AnomalRoil Pretty much the same command except `-q`. This is what I'm running on a 1.2M hits log.

    goaccess access.log --log-format=COMBINED

That's right, from my experience, the speed is certainly CPU-dependent. Are you able to test this out on a different machine, perhaps a laptop?

That's correct, `--keep-db-files --load-from-disk` are TC options. If you don't need to build a DB, then building without TC will give you better performance at the cost of limiting the dataset size to the amount of available physical memory. The default hash tables don't have the pointer overhead on integers - so definitely helps to keep memory low.

**Comment by allinurl** [comment]
@TerraTech While I do agree that having both would be nice, I don't know if it would be practical considering the maintenance of it. Though, I'm tempted to keep TC if I could reproduce the database corruption (e.g., #923) occurring to some folks and see if a workaround can be added. Again, I still need to see how LMDB performs so I'm not sure yet if it would even make it upstream, but there's a chance. Other than rolling our own db, I don't know if there are any other choices that satisfy goaccess requirements, perhaps redis can help? however, not sure if the heavy dependency is worth it.

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

[**v1.4**](https://goaccess.io/download) has been released.

I've added new performance metrics in the [**FAQ**](https://goaccess.io/faq#performance).
