### ISSUE TITLE
RFC: JSON external browser list

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#961]
How would you feel about shifting the browsers data out of browsers.c into an external JSON file?  It would seem that it would be better for keeping up with browser additions without having to compile a new goaccess binary.  The JSON file should also specify a format version specifier in case the structure should ever change.

Right now, how browsers are handled just isn't flexible or responsive for future changes/additions.

**Comment by allinurl** [comment]
The plan is to address this on #560. The only difference is that it loads all browsers from a text file. I like even better the idea of a JSON file, however, I'm hesitant of adding a new dependency for the JSON parser.

**Comment by TerraTech** [comment]
Understood, I'd be fine with a straight up text file since the format should be somewhat simple.  The only thorn would be selecting a non-colliding field delimiter.

**Comment by TerraTech** [comment]
One minor critique though, you already allow for tokyocabinet (which can be hit/miss on some distros) along with GeoIP.  Given that they aren't hard dependencies, I'd say adding a JSON library wouldn't be much of a stretch given that JSON libs should be available for just about any distro.  It would also allow the usage of standard JSON handling routines that could provide for report output validation.

Seems that ['json-c'](https://github.com/json-c/json-c) is a safe bet as it is available on Ubuntu/Gentoo/Fedora/RHEL.  Sometimes relying on a supported and standardized library is better than trying to roll one's own for the sake of removing an external dependency.

But alas, you've already rolled your own JSON handling routines and using ```json-c``` for the browser list might be a bit overkill when the list can be a simple delimited text file.

**Comment by allinurl** [comment]
I'm with you that a JSON library would come in handy, especially since the HTML output it's pretty much built from a single JSON string. Not so long ago I was in need for some basic JSON parsing routines but I couldn't find one that would do the job without having to include a bunch of files. I'd love to see a single-file (or a few) library with basic functionality that I can incorporate into the code. 

I'll definitely consider adding one as the project grows. Closing this for now since the current plan is to implement it using a simple delimited text file. Thanks for the feedback!
