### ISSUE TITLE
GoAccess (Log Analysis) vs Google Analytics (Client-Side Script Analysis) with regard to Measuring Human Users

### ISSUE THREAD

**Issue by technotarek** [allinurl/goaccess#964]
Thx again for the support in the other thread. Everything is working as expected now. What I'd like to raise here, if you think it is appropriate, is a more philosophical issue about why some of us may be using your software (and similar alternatives). 

I first discovered your software in this article that popped up on HackerNews earlier this year: https://www.stavros.io/posts/scourge-web-analytics/. Its main point is that we shouldn't weigh down our websites with heavy scripts like Google Analytics. In addition, he makes the point that Google Analytics misses users that either have scripts disabled or perhaps block tracking specifically. So when he recommended GoAccess, I was excited to see if it would tell me how many users were actually missing from my Google Analtyics data. It's of great importance to me because I run some sites that display ads and the number of impressions is hugely important to prospective advertisers. 

After looking at my first few reports from GoAccess, I learned a lot. But unfortunately, I feel like I can't answer my question: How drastically is Google Analtyics under-reporting human users? 

Below I'm pasting my full elaboration of the issue, which I left as a comment on the aforementioned blog post. I'd love your take on it, as well as anyone else thinking about similar issues. As my comment below says at the end, your software does exactly what it advertises to do. It's great in that respect. My own issues with it are probably issues with log analysis as a whole -- not your software. If you think there's a more appropriate place for this discussion, please let me know. Thanks.

> I'm very sympathetic to the sentiments of your post, specifically around the issue of relying on Google Analytics when we know it misses a lot of users (because of blocking etc). So I went ahead and installed GoAccess. What I'm struggling with though is making decent use of what it provides. As you mentioned, it does it's best to isolate crawlers from non-crawlers (and even has an option to run a report that excludes known crawlers (--ignore-crawlers)).
> 
> The problem is that it's missing a lot of likely crawlers. Even after excluding known crawlers, my reports are showing that nearly 15% of unique visitors were using an "unknown" browser. Similarly, about 11% were from an "unknown OS". These make me think that I need to further discount what the reports show.
> 
> Ultimately my goal was to figure out how much Google Analytics is actually under reporting my visitors and get a more accurate read on the site's (human) traffic. Unfortunately, giving the issues above, it doesn't seem suitable to answer this question. Perhaps others out there that have come up with best practices to fully (or nearly fully) remove spiders, bots, crawlers and other non-human users from their log analysis? I'd love to participate in a wider discussion on that topic, where people contribute their best practices and tools.
> 
> As it stands now, GoAccess is reporting that my actual unique visitors are nearly 5x higher than reported by Google Analytics (having discounted as described above). In absolute terms, I'm talking about the difference between 300 and 1500 uniques per day! I wish I could know this were true with confidence, but I can't.
> 
> To your hope of having people discontinue use of products like Google Analytics, it's pretty hard given what I've described. The data disparity makes me skeptical about what I see from the competitors. And just to be clear, I'm not meaning to critique GoAccess directly. It works quite well, but just has clear data/filtering limitations if it or a similar tool is going to serve as a realistic replacement for Google Analytics.
>

**Comment by allinurl** [comment]
Thanks for posting this, it's always valuable to hear how people are using the tool. First let me start posting a couple of recent questions in regards to this that may answer some of your questions:

> **Unique visitors count much greater than Google Analytics**
>
> However, recently a similar question was asked (#789), and as I mentioned over there, Google Analytics counts unique visitors differently from goaccess and my assumption must be the same for Piwik.
> 
> Since both of them use cookies to track a visitor, then it's possible that the same user could visit your website using different IPs while the cookie still living in their browser (same laptop, different locations) — That could be one of the things you are experiencing.
> 
> On the other hand, GoAccess considers requests containing the same IP, same date (e.g., 12/Jun/2017), and the same user agent a unique visitor. This is due to the nature of GoAccess attempting to get an accurate picture of what's happening at the server level as opposed to a marketing level of your website.
> 
> I'd suggest taking a small data set from your access log, e.g., 50-100 lines and then parsing it with goaccess. Take a look at the unique visitors count and see if it matches what you expect by looking at the log entries manually.
> 
> Now if you can run the same data set in any of the other tools (probably not possible with Google Analytics), then you may get an idea on how the numbers differ. 

**AND**

> **Unique visitors count different than Google Analytics**
>

> By default, GoAccess counts crawlers/bots as legitimate visitors. You can stop counting them using --ignore-crawlers. However, since it's not possible to account for all bots out there, even after you disable the most popular ones, you may still get a few in your logs.
> 
> Google Analytics keeps track of visitors using cookies, so if a browser has cookies or JavaScript disabled, then it won't keep track of it. This includes the now so popular adblockers and bots as well. GoAccess should be able to track these down fine since it works at the server level.
> 
> You can narrow down the unique visitors count to unique IPs. It will show you the total number in the upper-right corner of the panel.
> 
> You may be able to identify some bots/crawlers by listing the user agents of the given host. Passing -a will give you that list upon expanding a host in the hosts panel. Also, resolving the request IP with -d may give you a hint (assuming you are outputting HTML). It will add an extra column under the hosts panel (Note: -d will need to resolve all IPs and therefore the time it takes to parse will be longer)
> 
> I believe tracking visitors at the client level deflates the actual number of visitors (due to reason listed on #2). On the other hand, server-side tracking gives you a more accurate number at the cost of not knowing for sure if the client is a human behind a browser.

Having said that, there are a few things goaccess could do to better address at least the browser's panel count. 

1. Often we can find valid/legitimate bots having a URL within their UA e.g., `(compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)`. So the plan is to start parsing them, examine the result of it and start counting them as bots. This should certainly remove a great amount of "Unknowns" from that list (as many are not in the current list).
2. Let the user update the list via (JSON #961 or text file #560).

Now reducing the number of "Unknowns" from the OS panel is a bit more difficult since the majority of those unknowns are bots that don't contain an OS in their UA. We could make assumptions in here, however, I think it would be better to display them as "Bots" in this panel instead of "Unknowns".

In terms of flexibility, I think goaccess does give you a great amount of flexibility in terms of filtering as it allows the use of tools such grep, awk, sed, etc to do the heavy lifting. For instance, one filter that I find pretty informative in order to get a better sense on how many legitimate bots I'm getting is:

    tail -f -n +0 access.log | grep -i --line-buffered 'bot' | goaccess -

Note that #117 will add a built-in filtering capability, though, this is still in the works.

As I mentioned above, I think it's best to play with multiple small datasets from your logs and passing them to goaccess to see how many unique visitors will output vs a human and thorough inspection of those datasets may give you a better hint on what's going on.

**Comment by technotarek** [comment]
Thanks for the thoughtful response. I look forward to the future filtering options. As one last time, GoAccess works well, as advertised. Good work.
